# Generated by Django 2.2.6 on 2020-02-10 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_one_to_one_avoid_duplicates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposalcomment',
            old_name='comment_category',
            new_name='category',
        ),
    ]
