# Generated by Django 2.2.6 on 2020-02-10 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_fixes_comments_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalcommenttype',
            name='proposal',
        ),
    ]
