# Generated by Django 2.2.6 on 2020-02-10 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_uses_to_to_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalcomment',
            name='proposal',
            field=models.ForeignKey(help_text='Proposal that this comment refers to', on_delete=django.db.models.deletion.PROTECT, to='project_core.Proposal'),
        ),
    ]
