# Generated by Django 2.2.6 on 2020-02-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_auto_20200210_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalattachment',
            name='comment_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
