# Generated by Django 2.2.6 on 2020-02-11 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0009_add_category_attachments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposalattachmentcategory',
            old_name='comment_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='proposalcommentcategory',
            old_name='comment_category',
            new_name='category',
        ),
    ]
