# Generated by Django 2.2.6 on 2020-02-11 11:29

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0010_renames_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposalattachment',
            old_name='comment_text',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='proposalattachment',
            name='file',
            field=models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to='attachments/proposals/'),
        ),
    ]
