# Generated by Django 2.2.6 on 2020-02-11 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_core', '0101_auto_20200207_1144'),
        ('comments', '0011_renames_comment_text_to_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalattachment',
            name='text',
        ),
        migrations.AlterField(
            model_name='proposalattachment',
            name='category',
            field=models.ForeignKey(help_text='Category of the attachment', on_delete=django.db.models.deletion.PROTECT, to='comments.ProposalAttachmentCategory'),
        ),
        migrations.CreateModel(
            name='CallAttachmentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date and time at which the entry was created')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Date and time at which the entry was modified', null=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='comments.Category')),
                ('created_by', models.ForeignKey(blank=True, help_text='User by which the entry was created', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comments_callattachmentcategory_created_by_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, help_text='User by which the entry was modified', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comments_callattachmentcategory_modified_by_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Call Attachment Categories',
            },
        ),
        migrations.CreateModel(
            name='CallAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date and time at which the entry was created')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Date and time at which the entry was modified', null=True)),
                ('file', models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to='attachments/calls/')),
                ('call', models.ForeignKey(help_text='Call that this attachment belongs to', on_delete=django.db.models.deletion.PROTECT, to='project_core.Call')),
                ('category', models.ForeignKey(help_text='Category of the attachment', on_delete=django.db.models.deletion.PROTECT, to='comments.CallAttachmentCategory')),
                ('created_by', models.ForeignKey(blank=True, help_text='User by which the entry was created', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comments_callattachment_created_by_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, help_text='User by which the entry was modified', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comments_callattachment_modified_by_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
