# Generated by Django 2.2.6 on 2020-02-12 12:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0013_adds_call_comment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='callattachment',
            name='text',
            field=models.TextField(blank=True, help_text='Comment of the attachment', null=True),
        ),
        migrations.AddField(
            model_name='proposalattachment',
            name='text',
            field=models.TextField(blank=True, help_text='Comment of the attachment', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='callattachment',
            unique_together={('created_on', 'created_by')},
        ),
        migrations.AlterUniqueTogether(
            name='proposalattachment',
            unique_together={('created_on', 'created_by')},
        ),
    ]
