# Generated by Django 2.2.6 on 2020-02-12 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0102_colour'),
        ('comments', '0014_adds_txt_to_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='project_core.Colour'),
        ),
    ]
