# Generated by Django 2.2.6 on 2020-02-12 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0015_category_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='color',
            new_name='colour',
        ),
    ]
