# Generated by Django 2.2.6 on 2020-02-13 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0016_british_spelling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='colour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='colours.ColourPair'),
        ),
    ]
