# Generated by Django 3.0.3 on 2020-02-14 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0017_uses_model_from_colour_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
    ]
