# Generated by Django 3.0.3 on 2020-02-27 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0018_rename_category_field_to_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callattachment',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='callattachmentcategory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='callattachmentcategory',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='callcomment',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='callcommentcategory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='callcommentcategory',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='category',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='proposalattachment',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='proposalattachmentcategory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='proposalattachmentcategory',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='proposalcomment',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='proposalcommentcategory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='proposalcommentcategory',
            name='modified_by',
        ),
    ]
