# Generated by Django 3.0.3 on 2020-03-04 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('evaluation', '0010_file_name_processed_on_save'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0019_removes_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalEvaluationCommentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date and time at which the entry was created')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Date and time at which the entry was modified', null=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='comments.Category')),
            ],
            options={
                'verbose_name_plural': 'Proposal Evaluation Comment Categories',
            },
        ),
        migrations.CreateModel(
            name='ProposalEvaluationAttachmentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date and time at which the entry was created')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Date and time at which the entry was modified', null=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='comments.Category')),
            ],
            options={
                'verbose_name_plural': 'Proposal Evaluation Attachment Categories',
            },
        ),
        migrations.CreateModel(
            name='ProposalEvaluationComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date and time at which the entry was created')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Date and time at which the entry was modified', null=True)),
                ('text', models.TextField(help_text='Comment text')),
                ('category', models.ForeignKey(help_text='Type of comment', on_delete=django.db.models.deletion.PROTECT, to='comments.ProposalEvaluationCommentCategory')),
                ('created_by', models.ForeignKey(blank=True, help_text='User by which the entry was created', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comments_proposalevaluationcomment_created_by_related', to=settings.AUTH_USER_MODEL)),
                ('proposal_evaluation', models.ForeignKey(help_text='Proposal Evaluation about which the comment was made', on_delete=django.db.models.deletion.PROTECT, to='evaluation.ProposalEvaluation')),
            ],
            options={
                'unique_together': {('proposal_evaluation', 'created_on', 'created_by')},
            },
        ),
        migrations.CreateModel(
            name='ProposalEvaluationAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date and time at which the entry was created')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Date and time at which the entry was modified', null=True)),
                ('text', models.TextField(blank=True, help_text='Comment of the attachment', null=True)),
                ('file', models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to='attachments/proposal_evaluation/')),
                ('category', models.ForeignKey(help_text='Category of the attachment', on_delete=django.db.models.deletion.PROTECT, to='comments.ProposalEvaluationAttachmentCategory')),
                ('created_by', models.ForeignKey(blank=True, help_text='User by which the entry was created', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comments_proposalevaluationattachment_created_by_related', to=settings.AUTH_USER_MODEL)),
                ('proposal_evaluation', models.ForeignKey(help_text='Proposal Evaluation that this attachment belongs to', on_delete=django.db.models.deletion.PROTECT, to='evaluation.ProposalEvaluation')),
            ],
            options={
                'abstract': False,
                'unique_together': {('created_on', 'created_by')},
            },
        ),
    ]
