# Generated by Django 3.0.3 on 2020-03-04 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluation', '0010_file_name_processed_on_save'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0020_proposalevaluationattachment_proposalevaluationattachmentcategory_proposalevaluationcomment_proposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallEvaluationCommentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date and time at which the entry was created')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Date and time at which the entry was modified', null=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='comments.Category')),
            ],
            options={
                'verbose_name_plural': 'Call Evaluation Comment Categories',
            },
        ),
        migrations.CreateModel(
            name='CallEvaluationComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date and time at which the entry was created')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Date and time at which the entry was modified', null=True)),
                ('text', models.TextField(help_text='Comment text')),
                ('call_evaluation', models.ForeignKey(help_text='Type of comment', on_delete=django.db.models.deletion.PROTECT, to='comments.CallEvaluationCommentCategory')),
                ('created_by', models.ForeignKey(blank=True, help_text='User by which the entry was created', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comments_callevaluationcomment_created_by_related', to=settings.AUTH_USER_MODEL)),
                ('proposal_evaluation', models.ForeignKey(help_text='Call Evaluation about which the comment was made', on_delete=django.db.models.deletion.PROTECT, to='evaluation.ProposalEvaluation')),
            ],
            options={
                'unique_together': {('call_evaluation', 'created_on', 'created_by')},
            },
        ),
    ]
