# Generated by Django 3.0.3 on 2020-03-04 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluation', '0010_file_name_processed_on_save'),
        ('comments', '0021_callevaluationcomment_callevaluationcommentcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callevaluationcomment',
            name='call_evaluation',
            field=models.ForeignKey(help_text='Type of comment', on_delete=django.db.models.deletion.PROTECT, to='evaluation.CallEvaluation'),
        ),
    ]
