# Generated by Django 3.0.3 on 2020-03-04 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluation', '0010_file_name_processed_on_save'),
        ('comments', '0022_fixes_fk_to_the_right_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callevaluationcomment',
            name='proposal_evaluation',
        ),
        migrations.AddField(
            model_name='callevaluationcomment',
            name='category',
            field=models.ForeignKey(default=None, help_text='Type of comment', on_delete=django.db.models.deletion.PROTECT, to='comments.ProposalEvaluationCommentCategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='callevaluationcomment',
            name='call_evaluation',
            field=models.ForeignKey(help_text='Call Evaluation about which the comment was made', on_delete=django.db.models.deletion.PROTECT, to='evaluation.CallEvaluation'),
        ),
    ]
