# Generated by Django 3.0.3 on 2020-03-19 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_core', '0111_remove_project_duration_months'),
        ('comments', '0024_fixes_foreign_key_in_call_evaluation_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCommentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date and time at which the entry was created')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Date and time at which the entry was modified', null=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='comments.Category')),
            ],
            options={
                'verbose_name_plural': 'Project Comment Categories',
            },
        ),
        migrations.CreateModel(
            name='ProjectAttachmentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date and time at which the entry was created')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Date and time at which the entry was modified', null=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='comments.Category')),
            ],
            options={
                'verbose_name_plural': 'Project Attachment Categories',
            },
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date and time at which the entry was created')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Date and time at which the entry was modified', null=True)),
                ('text', models.TextField(help_text='Comment text')),
                ('category', models.ForeignKey(help_text='Type of comment', on_delete=django.db.models.deletion.PROTECT, to='comments.ProjectCommentCategory')),
                ('created_by', models.ForeignKey(blank=True, help_text='User by which the entry was created', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comments_projectcomment_created_by_related', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='Project about which the comment was made', on_delete=django.db.models.deletion.PROTECT, to='project_core.Project')),
            ],
            options={
                'unique_together': {('project', 'created_on', 'created_by')},
            },
        ),
        migrations.CreateModel(
            name='ProjectAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date and time at which the entry was created')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Date and time at which the entry was modified', null=True)),
                ('text', models.TextField(blank=True, help_text='Comment of the attachment', null=True)),
                ('file', models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to='attachments/project/')),
                ('category', models.ForeignKey(help_text='Category of the attachment', on_delete=django.db.models.deletion.PROTECT, to='comments.ProjectAttachmentCategory')),
                ('created_by', models.ForeignKey(blank=True, help_text='User by which the entry was created', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comments_projectattachment_created_by_related', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='Project that this attachment belongs to', on_delete=django.db.models.deletion.PROTECT, to='project_core.Project')),
            ],
            options={
                'abstract': False,
                'unique_together': {('created_on', 'created_by')},
            },
        ),
    ]
