# Generated by Django 3.0.3 on 2020-04-02 14:21

import comments.models
from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0025_projectattachment_projectattachmentcategory_projectcomment_projectcommentcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalattachment',
            name='file',
            field=models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=comments.models.proposal_attachment_rename),
        ),
    ]
