# Generated by Django 3.0.3 on 2020-04-02 14:36

import comments.models
from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0026_uses_function_to_rename_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callattachment',
            name='file',
            field=models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=comments.models.call_attachment_rename),
        ),
        migrations.AlterField(
            model_name='projectattachment',
            name='file',
            field=models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=comments.models.proposal_evaluation_rename),
        ),
        migrations.AlterField(
            model_name='proposalevaluationattachment',
            name='file',
            field=models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=comments.models.proposal_evaluation_rename),
        ),
    ]
