# Generated by Django 3.0.5 on 2020-05-06 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grant_management', '0027_bblog_post_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0027_improve_paths_object_storage_for_comment_attachments'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceCommentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date and time at which the entry was created')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Date and time at which the entry was modified', null=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='comments.Category')),
            ],
            options={
                'verbose_name_plural': 'Invoice Comment Categories',
            },
        ),
        migrations.CreateModel(
            name='InvoiceComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date and time at which the entry was created')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Date and time at which the entry was modified', null=True)),
                ('text', models.TextField(help_text='Comment text')),
                ('category', models.ForeignKey(help_text='Type of comment', on_delete=django.db.models.deletion.PROTECT, to='comments.CallEvaluationCommentCategory')),
                ('created_by', models.ForeignKey(blank=True, help_text='User by which the entry was created', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comments_invoicecomment_created_by_related', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(help_text='Call Evaluation about which the comment was made', on_delete=django.db.models.deletion.PROTECT, to='grant_management.Invoice')),
            ],
            options={
                'unique_together': {('invoice', 'created_on', 'created_by')},
            },
        ),
    ]
