# Generated by Django 3.0.5 on 2020-05-20 10:45

import comments.models
from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0029_fixes_invoice_category_foreign_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectattachment',
            name='file',
            field=models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=comments.models.project_attachment_rename),
        ),
    ]
