# Generated by Django 3.0.5 on 2020-05-29 13:48

import comments.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grant_management', '0048_installment_helptext'),
        ('comments', '0030_auto_20200520_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantAgreementCommentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date and time at which the entry was created')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Date and time at which the entry was modified', null=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='comments.Category')),
            ],
            options={
                'verbose_name_plural': 'GrantAgreement Comment Categories',
            },
        ),
        migrations.CreateModel(
            name='GrantAgreementAttachmentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date and time at which the entry was created')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Date and time at which the entry was modified', null=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='comments.Category')),
            ],
            options={
                'verbose_name_plural': 'Grant Agreement Attachment Categories',
            },
        ),
        migrations.CreateModel(
            name='GrantAgreementComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date and time at which the entry was created')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Date and time at which the entry was modified', null=True)),
                ('text', models.TextField(help_text='Comment text')),
                ('category', models.ForeignKey(help_text='Type of comment', on_delete=django.db.models.deletion.PROTECT, to='comments.GrantAgreementCommentCategory')),
                ('created_by', models.ForeignKey(blank=True, help_text='User by which the entry was created', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comments_grantagreementcomment_created_by_related', to=settings.AUTH_USER_MODEL)),
                ('grant_agreement', models.ForeignKey(help_text='GrantAgreement about which the comment was made', on_delete=django.db.models.deletion.PROTECT, to='grant_management.GrantAgreement')),
            ],
            options={
                'unique_together': {('grant_agreement', 'created_on', 'created_by')},
            },
        ),
        migrations.CreateModel(
            name='GrantAgreementAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date and time at which the entry was created')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Date and time at which the entry was modified', null=True)),
                ('text', models.TextField(blank=True, help_text='Comment of the attachment', null=True)),
                ('file', models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=comments.models.grant_agreement_attachment_rename)),
                ('category', models.ForeignKey(help_text='Category of the attachment', on_delete=django.db.models.deletion.PROTECT, to='comments.GrantAgreementAttachmentCategory')),
                ('created_by', models.ForeignKey(blank=True, help_text='User by which the entry was created', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comments_grantagreementattachment_created_by_related', to=settings.AUTH_USER_MODEL)),
                ('grant_agreement', models.ForeignKey(help_text='GrantAgreement that this attachment belongs to', on_delete=django.db.models.deletion.PROTECT, to='grant_management.GrantAgreement')),
            ],
            options={
                'abstract': False,
                'unique_together': {('created_on', 'created_by')},
            },
        ),
    ]
