# Generated by Django 3.0.5 on 2020-06-02 13:54

from django.db import migrations


def add_categories(apps, schema_editor):
    GrantAgreementAttachmentCategory = apps.get_model('comments', 'GrantAgreementAttachmentCategory')
    GrantAgreementCommentCategory = apps.get_model('comments', 'GrantAgreementCommentCategory')
    GrantAgreementComment = apps.get_model('comments', 'GrantAgreementComment')
    GrantAgreementAttachment = apps.get_model('comments', 'GrantAgreementAttachment')
    InvoiceCommentCategory = apps.get_model('comments', 'InvoiceCommentCategory')
    InvoiceComment = apps.get_model('comments', 'InvoiceComment')
    ProjectComment = apps.get_model('comments', 'ProjectComment')
    ProjectAttachment = apps.get_model('comments', 'ProjectAttachment')
    ProjectCommentCategory = apps.get_model('comments', 'ProjectCommentCategory')
    ProjectAttachmentsCategory = apps.get_model('comments', 'ProjectAttachmentCategory')
    ProposalAttachmentCategory = apps.get_model('comments', 'ProjectAttachmentCategory')
    ProposalCommentCategory = apps.get_model('comments', 'ProposalCommentCategory')
    ProposalEvaluationAttachmentCategory = apps.get_model('comments', 'ProposalEvaluationAttachmentCategory')
    ProposalEvaluationCommentCategory = apps.get_model('comments', 'ProposalEvaluationCommentCategory')

    Category = apps.get_model('comments', 'Category')

    ColourPair = apps.get_model('colours', 'ColourPair')

    # Creates new categories
    Category.objects.get_or_create(name='Partners', colour=ColourPair.objects.get(description='Sunflower with light font'))
    Category.objects.get_or_create(name='Milestones', colour=ColourPair.objects.get(description='Peter river with light font'))
    Category.objects.get_or_create(name='Documentation', colour=ColourPair.objects.get(description='Emerald with light font'))
    Category.objects.get_or_create(name='Payment', colour=ColourPair.objects.get(description='Turquoise with light font'))

    # Creates new Categories for the things
    InvoiceComment.objects.all().delete()
    InvoiceCommentCategory.objects.all().delete()
    InvoiceCommentCategory.objects.get_or_create(category=Category.objects.get(name='Correspondence'))
    InvoiceCommentCategory.objects.get_or_create(category=Category.objects.get(name='Deadline'))
    InvoiceCommentCategory.objects.get_or_create(category=Category.objects.get(name='Payment'))

    GrantAgreementComment.objects.all().delete()
    GrantAgreementCommentCategory.objects.all().delete()
    GrantAgreementCommentCategory.objects.get_or_create(category=Category.objects.get(name='Correspondence'))
    GrantAgreementCommentCategory.objects.get_or_create(category=Category.objects.get(name='Deadline'))

    GrantAgreementAttachment.objects.all().delete()
    GrantAgreementAttachmentCategory.objects.all().delete()
    GrantAgreementAttachmentCategory.objects.get_or_create(category=Category.objects.get(name='Correspondence'))

    ProjectComment.objects.all().delete()
    ProjectCommentCategory.objects.all().delete()
    ProjectCommentCategory.objects.get_or_create(category=Category.objects.get(name='Correspondence'))
    ProjectCommentCategory.objects.get_or_create(category=Category.objects.get(name='Finance'))
    ProjectCommentCategory.objects.get_or_create(category=Category.objects.get(name='Outreach'))
    ProjectCommentCategory.objects.get_or_create(category=Category.objects.get(name='Milestones'))
    ProjectCommentCategory.objects.get_or_create(category=Category.objects.get(name='Reports'))

    ProjectAttachment.objects.all().delete()
    ProjectAttachmentsCategory.objects.all().delete()
    ProjectAttachmentsCategory.objects.get_or_create(category=Category.objects.get(name='Correspondence'))
    ProjectAttachmentsCategory.objects.get_or_create(category=Category.objects.get(name='Documentation'))

    ProposalAttachmentCategory.objects.get_or_create(category=Category.objects.get(name='Correspondence'))
    ProposalAttachmentCategory.objects.get_or_create(category=Category.objects.get(name='Documentation'))

    ProposalCommentCategory.objects.get_or_create(category=Category.objects.get(name='Budget'))
    ProposalCommentCategory.objects.get_or_create(category=Category.objects.get(name='Partners'))
    ProposalCommentCategory.objects.get_or_create(category=Category.objects.get(name='Correspondence'))
    ProposalCommentCategory.objects.get_or_create(category=Category.objects.get(name='Deadline'))

    ProposalEvaluationAttachmentCategory.objects.get_or_create(category=Category.objects.get(name='Correspondence'))
    ProposalEvaluationAttachmentCategory.objects.get_or_create(category=Category.objects.get(name='Evaluation'))
    ProposalEvaluationAttachmentCategory.objects.get_or_create(category=Category.objects.get(name='Documentation'))

    ProposalEvaluationCommentCategory.objects.get_or_create(category=Category.objects.get(name='Correspondence'))


class Migration(migrations.Migration):
    dependencies = [
        ('comments', '0032_fix_plurals'),
    ]

    operations = [
        migrations.RunPython(add_categories),
    ]
