# Generated by Django 3.0.10 on 2020-09-21 10:38

import comments.models
from django.db import migrations, models
import project_core.utils.utils
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0033_add_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callattachment',
            name='file',
            field=models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=comments.models.call_attachment_rename, validators=[*project_core.utils.utils.management_file_validator()]),
        ),
        migrations.AlterField(
            model_name='grantagreementattachment',
            name='file',
            field=models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=comments.models.grant_agreement_attachment_rename, validators=[*project_core.utils.utils.management_file_validator()]),
        ),
        migrations.AlterField(
            model_name='projectattachment',
            name='file',
            field=models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=comments.models.project_attachment_rename, validators=[*project_core.utils.utils.management_file_validator()]),
        ),
        migrations.AlterField(
            model_name='proposalattachment',
            name='file',
            field=models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=comments.models.proposal_attachment_rename, validators=[*project_core.utils.utils.management_file_validator()]),
        ),
        migrations.AlterField(
            model_name='proposalevaluationattachment',
            name='file',
            field=models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=comments.models.proposal_evaluation_rename, validators=[*project_core.utils.utils.management_file_validator()]),
        ),
    ]
