version: '3.6'

services:
  project-application:
    container_name: project-application-staging
    env_file:
      - ${PROJECT_APPLICATION_STAGING_ENV_FILE}
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: project-application-staging.django

  reverse-proxy:
    container_name: project-application-reverse-proxy-staging
    environment:
      - VIRTUAL_HOST=${PROJECT_APPLICATION_STAGING_DOMAINS}
      - LETSENCRYPT_HOST=${PROJECT_APPLICATION_STAGING_DOMAINS}
    volumes:
      - ./nginx-staging/nginx.conf:/etc/nginx/nginx.conf
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: project-application-staging.nginx

  database:
    container_name: project-application-database-staging
    environment:
      - MYSQL_USER=${PROJECT_APPLICATION_STAGING_DB_USER}
      - MYSQL_PASSWORD=${PROJECT_APPLICATION_STAGING_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${PROJECT_APPLICATION_STAGING_ROOT_PASSWORD}
    ports:
      - "127.0.0.1:33308:3306"
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: project-application-application.mariadb

secrets:
  project_application_mysql.conf:
    file: ${PROJECT_APPLICATION_STAGING_MYSQL_CONF_PATH}
  project_application_htpasswd:
    file: ${PROJECT_APPLICATION_STAGING_HTPASSWD}
