version: '3.6'

services:
  project-application:
    env_file:
      - ${PROJECT_APPLICATION_ENV_FILE}
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: project-application.django

  reverse-proxy:
    environment:
      - VIRTUAL_HOST=${PROJECT_APPLICATION_DOMAINS}
      - LETSENCRYPT_HOST=${PROJECT_APPLICATION_DOMAINS}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: project-application.nginx

  database:
    environment:
      - MYSQL_USER=${PROJECT_APPLICATION_DB_USER}
      - MYSQL_PASSWORD=${PROJECT_APPLICATION_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${PROJECT_APPLICATION_ROOT_PASSWORD}
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: project-application.mariadb

secrets:
  project_application_mysql.conf:
    file: ${PROJECT_APPLICATION_MYSQL_CONF_PATH}
  project_application_htpasswd:
    file: ${PROJECT_APPLICATION_HTPASSWD}
