# Generated by Django 3.0.10 on 2020-10-23 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_core', '0142_fix_physicalperson_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingInstrumentYearMissingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finance_year', models.IntegerField()),
                ('funding_instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project_core.FundingInstrument')),
            ],
        ),
    ]
