# Generated by Django 3.0.10 on 2020-10-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundinginstrumentyearmissingdata',
            options={'verbose_name_plural': 'Funding Instrument Year Missing Data'},
        ),
        migrations.AddField(
            model_name='fundinginstrumentyearmissingdata',
            name='description',
            field=models.TextField(default='', help_text='Reason that there is missing data. It might be shown in the management'),
            preserve_default=False,
        ),
    ]
