# Generated by Django 3.0.10 on 2020-10-23 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0142_fix_physicalperson_plural'),
        ('reporting', '0003_funding_instrument_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundinginstrumentyearmissingdata',
            name='missing_data_type',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fundinginstrumentyearmissingdata',
            name='finance_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fundinginstrumentyearmissingdata',
            name='funding_instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='project_core.FundingInstrument'),
        ),
    ]
