# Generated by Django 2.2.4 on 2019-08-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notable_date', models.CharField(help_text='Description of notable date', max_length=128)),
                ('date', models.DateTimeField(help_text='Date and time of notable date', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(help_text='Full name of the call', max_length=128)),
                ('short_name', models.CharField(blank=True, help_text='Short name or acronym of the call', max_length=64, null=True)),
                ('description', models.TextField(help_text='Description of the call that can be used to distinguish it from others')),
                ('dates', models.ManyToManyField(help_text='Notable date related to the call', to='project_core.Date')),
            ],
        ),
    ]
