# Generated by Django 2.2.4 on 2019-09-20 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0002_proposal_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeographicalArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(help_text='Name of geographic area', max_length=100)),
                ('definition', models.CharField(help_text='Detailed description of the geographic area to avoid duplicate entries or confusion', max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='proposal',
            name='geographical_area',
            field=models.ForeignKey(help_text='Description of the geographical area covered by the proposal', on_delete=django.db.models.deletion.PROTECT, to='project_core.GeographicalArea'),
        ),
        migrations.DeleteModel(
            name='GeographicArea',
        ),
    ]
