# Generated by Django 2.2.4 on 2019-09-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0003_change_name_geographicarea'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetcategory',
            options={'verbose_name_plural': 'Budget categories'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='fundingstatus',
            options={'verbose_name_plural': 'Funding status'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'People'},
        ),
        migrations.AlterModelOptions(
            name='proposalstatus',
            options={'verbose_name_plural': 'Proposal status'},
        ),
        migrations.RenameField(
            model_name='proposal',
            old_name='start_time_frame',
            new_name='start_timeframe',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='geographical_area',
        ),
        migrations.AddField(
            model_name='proposal',
            name='geographical_area',
            field=models.ManyToManyField(help_text='Description of the geographical area covered by the proposal', to='project_core.GeographicalArea'),
        ),
    ]
