# Generated by Django 2.2.4 on 2019-09-20 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0004_auto_proposal_model_corrections'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('answer_type', models.CharField(choices=[('T', 'TextField')], help_text='Type of field that should be applied to the question answer', max_length=5)),
                ('answer_max_length', models.IntegerField(blank=True, help_text='Maximum number of words that can be specified to the answer of a question', null=True)),
                ('call', models.ForeignKey(help_text='Questions for a call', on_delete=django.db.models.deletion.PROTECT, to='project_core.Call')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='description',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='logistics_requirements',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='requested_funds_explanation',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='summary',
        ),
        migrations.AddField(
            model_name='proposal',
            name='call',
            field=models.ForeignKey(default=1, help_text='Call to which the proposal relates', on_delete=django.db.models.deletion.PROTECT, to='project_core.Call'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProposalQAText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(help_text='Answer to the question from the call')),
                ('call_question', models.ForeignKey(help_text='Question from the call', on_delete=django.db.models.deletion.PROTECT, to='project_core.CallQuestion')),
                ('proposal', models.ForeignKey(help_text='Questions and answers for a proposal', on_delete=django.db.models.deletion.PROTECT, to='project_core.Proposal')),
            ],
            options={
                'verbose_name_plural': 'Proposal question-answer (text)',
            },
        ),
    ]
