# Generated by Django 2.2.4 on 2019-09-24 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0005_create_questions_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='geographical_area',
            new_name='geographical_areas',
        ),
    ]
