# Generated by Django 2.2.4 on 2019-09-24 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0006_rename_proposal_geographical_area_to_areas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='organisation',
            new_name='organisations',
        ),
    ]
