# Generated by Django 2.2.4 on 2019-09-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0008_auto_add_unique_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposedbudgetitem',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
