# Generated by Django 2.2.4 on 2019-09-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0009_budgetdetails_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='callquestion',
            name='question_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
