# Generated by Django 2.2.6 on 2019-10-02 13:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0010_callquestion_question_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
