# Generated by Django 2.2.6 on 2019-10-04 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0012_proposal_uuid_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(help_text='Name of career stage', max_length=50)),
                ('description', models.CharField(help_text='Description of the career stage', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='Name of role', max_length=50)),
                ('description', models.CharField(help_text='Description of role to distinguish it from others', max_length=200)),
                ('type', models.CharField(choices=[('Proposal', 'Proposal'), ('Project', 'Project'), ('Expedition', 'Expedition')], help_text='Part of the application to which the role refers, determining where it can be used in some cases', max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='callquestion',
            name='question_description',
            field=models.TextField(blank=True, help_text='Description that should go alongside the question text by way of explanation for completion of answer', null=True),
        ),
        migrations.AlterField(
            model_name='callquestion',
            name='question_text',
            field=models.TextField(help_text='Text of a question'),
        ),
        migrations.AlterField(
            model_name='proposedbudgetitem',
            name='category',
            field=models.ForeignKey(help_text='Name of the budget item', on_delete=django.db.models.deletion.PROTECT, to='project_core.BudgetCategory'),
        ),
        migrations.AlterField(
            model_name='proposedbudgetitem',
            name='details',
            field=models.TextField(blank=True, help_text='Details of the budget item'),
        ),
        migrations.CreateModel(
            name='ProposalPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_description', models.TextField(help_text='Description of what the person will be doing')),
                ('competences', models.TextField(help_text='Description of the competences of the person')),
                ('career_stage', models.ForeignKey(help_text='Stage of the person in the career', on_delete=django.db.models.deletion.PROTECT, to='project_core.CareerStage')),
                ('person', models.ForeignKey(help_text='Person that is a partner', on_delete=django.db.models.deletion.PROTECT, to='project_core.Person')),
                ('proposal', models.ForeignKey(help_text='Proposal to on which the partner is collaborating', on_delete=django.db.models.deletion.PROTECT, to='project_core.Proposal')),
                ('role', models.ForeignKey(help_text='Role of the person', on_delete=django.db.models.deletion.PROTECT, to='project_core.Role')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
