# Generated by Django 2.2.6 on 2019-10-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0013_create_proposal_partner_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='Text of a question')),
                ('question_description', models.TextField(blank=True, help_text='Description that should go alongside the question text by way of explanation for completion of answer', null=True)),
                ('answer_type', models.CharField(choices=[('Text', 'Text')], default='Text', help_text='Type of field that should be applied to the question answer', max_length=5)),
                ('answer_max_length', models.IntegerField(blank=True, help_text='Maximum number of words that can be specified to the answer of a question', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='contact',
            name='email_address',
            field=models.EmailField(help_text='Email address', max_length=254),
        ),
    ]
