# Generated by Django 2.2.6 on 2019-10-04 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0014_adds_abstract_question_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of a step', max_length=60)),
                ('description', models.CharField(help_text='Description of a step', max_length=200)),
                ('call', models.ForeignKey(help_text='Step within a call', on_delete=django.db.models.deletion.PROTECT, to='project_core.Call')),
            ],
        ),
        migrations.AlterField(
            model_name='stepdate',
            name='step',
            field=models.ForeignKey(help_text='Name of step', max_length=128, on_delete=django.db.models.deletion.PROTECT, to='project_core.StepType'),
        ),
        migrations.DeleteModel(
            name='Step',
        ),
    ]
