# Generated by Django 2.2.6 on 2019-10-04 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0015_refactor_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(help_text='Date and time of notable date', max_length=64)),
                ('call', models.ForeignKey(help_text='Step within a call', on_delete=django.db.models.deletion.PROTECT, to='project_core.Call')),
            ],
        ),
        migrations.RemoveField(
            model_name='steptype',
            name='call',
        ),
        migrations.DeleteModel(
            name='StepDate',
        ),
        migrations.AddField(
            model_name='step',
            name='step',
            field=models.ForeignKey(help_text='Name of step', max_length=128, on_delete=django.db.models.deletion.PROTECT, to='project_core.StepType'),
        ),
    ]
