# Generated by Django 2.2.6 on 2019-10-07 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0016_refactor_stepdate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='TemplateQuestion',
        ),
    ]
