# Generated by Django 2.2.6 on 2019-10-07 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0017_refactor_question_templatequestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='callquestion',
            name='question',
            field=models.ForeignKey(default=1, help_text='Template question on which this call question is based', on_delete=django.db.models.deletion.PROTECT, to='project_core.TemplateQuestion'),
            preserve_default=False,
        ),
    ]
