# Generated by Django 2.2.6 on 2019-10-07 12:16

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0019_add_fields_to_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='callquestion',
            name='order',
            field=models.IntegerField(default=1, help_text='Use the integer order to order the questions', validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='callquestion',
            name='time_added',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time at which the question was added to the call'),
        ),
    ]
