# Generated by Django 2.2.6 on 2019-10-07 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0020_add_call_question_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='careerstage',
            old_name='stage',
            new_name='name',
        ),
    ]
