# Generated by Django 2.2.6 on 2019-10-07 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0021_careerstage_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='role',
            new_name='name',
        ),
    ]
