# Generated by Django 2.2.6 on 2019-10-07 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0022_role_to_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geographicalarea',
            old_name='area',
            new_name='name',
        ),
    ]
