# Generated by Django 2.2.6 on 2019-10-07 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_core', '0023_geographicalarea_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='address',
        ),
        migrations.AddField(
            model_name='organisation',
            name='city',
            field=models.CharField(default='street', help_text='City in which the organisation is based', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisation',
            name='postal_code',
            field=models.CharField(default='postcode', help_text='Postal code of the organisation', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisation',
            name='street',
            field=models.CharField(default='street', help_text='Street address of the organisation', max_length=1000),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProposalComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Text of a comment')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time on which a comment was made')),
                ('proposal', models.ForeignKey(help_text='Proposal about which the comment was made', on_delete=django.db.models.deletion.PROTECT, to='project_core.Proposal')),
                ('user', models.ForeignKey(help_text='User by which the comment was made', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CallComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Text of a comment')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time on which a comment was made')),
                ('call', models.ForeignKey(help_text='Call about which the comment was made', on_delete=django.db.models.deletion.PROTECT, to='project_core.Call')),
                ('user', models.ForeignKey(help_text='User by which the comment was made', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
