# Generated by Django 2.2.6 on 2019-10-07 14:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_core', '0024_address_fields_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AlterField(
            model_name='budgetcategory',
            name='name',
            field=models.CharField(help_text='Name of the budget category', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='budget_maximum',
            field=models.DecimalField(decimal_places=2, help_text='Maximum amount that can be requested in the proposal budget', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='call',
            name='long_name',
            field=models.CharField(help_text='Full name of the call', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='callquestion',
            name='order',
            field=models.PositiveIntegerField(help_text='Use the integer order to order the questions', unique=True),
        ),
        migrations.AlterField(
            model_name='careerstage',
            name='name',
            field=models.CharField(help_text='Name of career stage', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email_address',
            field=models.EmailField(help_text='Email address', max_length=254, unique=True, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(help_text='Country name', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='fundingstatus',
            name='description',
            field=models.CharField(help_text='Description of the status', max_length=100),
        ),
        migrations.AlterField(
            model_name='fundingstatus',
            name='status',
            field=models.CharField(help_text='Name of the status', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='geographicalarea',
            name='name',
            field=models.CharField(help_text='Name of geographic area', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='street',
            field=models.CharField(help_text='Street address of the organisation', max_length=500),
        ),
        migrations.AlterField(
            model_name='persontitle',
            name='title',
            field=models.CharField(help_text='Personal or academic title used by a person', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='title',
            field=models.CharField(help_text='Title of the proposal being submitted', max_length=500),
        ),
        migrations.AlterField(
            model_name='proposalfundingitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount given in funding', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='proposalstatus',
            name='name',
            field=models.CharField(help_text='Name of the status of the proposal table', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='proposedbudgetitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Cost of category item', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='steptype',
            name='name',
            field=models.CharField(help_text='Name of a step', max_length=60, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='callcomment',
            unique_together={('call', 'time', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='callquestion',
            unique_together={('call', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('person', 'email_address')},
        ),
        migrations.AlterUniqueTogether(
            name='keyword',
            unique_together={('name', 'description')},
        ),
        migrations.AlterUniqueTogether(
            name='organisation',
            unique_together={('long_name', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='proposal',
            unique_together={('title', 'applicant', 'call')},
        ),
        migrations.AlterUniqueTogether(
            name='proposalcomment',
            unique_together={('proposal', 'time', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='proposalfundingitem',
            unique_together={('organisation', 'status', 'proposal', 'amount')},
        ),
        migrations.AlterUniqueTogether(
            name='proposalpartner',
            unique_together={('person', 'role', 'proposal')},
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('name', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='step',
            unique_together={('call', 'step')},
        ),
    ]
