# Generated by Django 2.2.6 on 2019-10-08 12:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0026_auto_changes_call_question_order_uniq'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Last date and time of modification'),
        ),
        migrations.AddField(
            model_name='country',
            name='source',
            field=models.CharField(help_text='Source of country name', max_length=100),
            preserve_default=False,
        ),
    ]
