# Generated by Django 2.2.6 on 2019-10-10 09:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0027_add_source_field_to_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of gender', max_length=20, unique=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time at which this gender was created')),
            ],
        ),
        migrations.CreateModel(
            name='PersonPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, help_text='Name of the working group, department, laboratory for which the person works', max_length=200, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time at which this person was created')),
                ('academic_title', models.ForeignKey(help_text='Title of the person', on_delete=django.db.models.deletion.PROTECT, to='project_core.PersonTitle')),
                ('organisations', models.ManyToManyField(help_text='Organisation(s) represented by the person', to='project_core.Organisation')),
            ],
            options={
                'verbose_name_plural': 'People from organisation(s)',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text='Source from which a UUID may originate', max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time at which this source was created')),
            ],
        ),
        migrations.RenameField(
            model_name='callquestion',
            old_name='time_added',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='proposalfundingitem',
            old_name='status',
            new_name='funding_status',
        ),
        migrations.RenameField(
            model_name='step',
            old_name='step',
            new_name='step_type',
        ),
        migrations.RemoveField(
            model_name='country',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='date_started',
        ),
        migrations.AddField(
            model_name='contact',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time at which this contact was created'),
        ),
        migrations.AddField(
            model_name='contact',
            name='entry',
            field=models.CharField(default='', help_text='Text of contact entry, such as phone number, pager etc.', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='method',
            field=models.CharField(choices=[('Office', 'Office'), ('Mobile', 'Mobile'), ('Email', 'Email')], default='', help_text='Type of contact method', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time created'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time (UTC) at which the proposal was first created'),
        ),
        migrations.AlterField(
            model_name='country',
            name='source',
            field=models.ForeignKey(help_text='Source of country name', on_delete=django.db.models.deletion.PROTECT, to='project_core.Source'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='applicant',
            field=models.ForeignKey(help_text='Main applicant of the proposal', on_delete=django.db.models.deletion.PROTECT, to='project_core.PersonPosition'),
        ),
        migrations.AlterField(
            model_name='proposalpartner',
            name='person',
            field=models.ForeignKey(help_text='Person that is a partner', on_delete=django.db.models.deletion.PROTECT, to='project_core.PersonPosition'),
        ),
        migrations.AlterUniqueTogether(
            name='proposalfundingitem',
            unique_together={('organisation', 'funding_status', 'proposal', 'amount')},
        ),
        migrations.AlterUniqueTogether(
            name='step',
            unique_together={('call', 'step_type')},
        ),
        migrations.CreateModel(
            name='PhysicalPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First name(s) of a person', max_length=100)),
                ('surname', models.CharField(help_text='Last name(s) of a person', max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time at which this person was created')),
                ('gender', models.ForeignKey(help_text='Gender with which the person identifies', on_delete=django.db.models.deletion.PROTECT, to='project_core.Gender')),
            ],
            options={
                'unique_together': {('first_name', 'surname')},
            },
        ),
        migrations.AddField(
            model_name='personposition',
            name='person',
            field=models.ForeignKey(help_text='A unique physical person', on_delete=django.db.models.deletion.PROTECT, to='project_core.PhysicalPerson'),
        ),
        migrations.AddField(
            model_name='contact',
            name='person_position',
            field=models.ForeignKey(default='', help_text='Person to whom the contact details belong', on_delete=django.db.models.deletion.PROTECT, to='project_core.PersonPosition'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('person_position', 'entry')},
        ),
        migrations.CreateModel(
            name='PersonUuid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(help_text='Unique identifier', max_length=150, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time at which this UUID was created')),
                ('person', models.OneToOneField(help_text='Person to which the UUID refers', on_delete=django.db.models.deletion.PROTECT, to='project_core.PhysicalPerson')),
                ('source', models.ForeignKey(help_text='Source of the UUID', on_delete=django.db.models.deletion.PROTECT, to='project_core.Source')),
            ],
            options={
                'abstract': False,
                'unique_together': {('uuid', 'source')},
            },
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='person',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='work_telephone',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
