# Generated by Django 2.2.6 on 2019-10-10 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0028_person_physical_person_person_position_small_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalperson',
            name='gender',
            field=models.ForeignKey(blank=True, help_text='Gender with which the person identifies', null=True, on_delete=django.db.models.deletion.PROTECT, to='project_core.Gender'),
        ),
    ]
