# Generated by Django 2.2.6 on 2019-10-11 14:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0029_gender_can_be_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonUid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(help_text='Unique identifier', max_length=150, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time at which this UID was created')),
                ('person', models.OneToOneField(help_text='Person to which the UID refers', on_delete=django.db.models.deletion.PROTECT, to='project_core.PhysicalPerson')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='callquestion',
            name='answer_max_length',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of words that can be specified to the answer of a question', null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='source',
            field=models.CharField(help_text='Source from which a UID may originate', max_length=100),
        ),
        migrations.AlterField(
            model_name='templatequestion',
            name='answer_max_length',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of words that can be specified to the answer of a question', null=True),
        ),
        migrations.DeleteModel(
            name='PersonUuid',
        ),
        migrations.AddField(
            model_name='personuid',
            name='source',
            field=models.ForeignKey(help_text='Source of the UID', on_delete=django.db.models.deletion.PROTECT, to='project_core.Source'),
        ),
        migrations.AlterUniqueTogether(
            name='personuid',
            unique_together={('uid', 'source')},
        ),
    ]
