# Generated by Django 2.2.6 on 2019-10-14 13:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0030_template_question_answer_max_length_positive_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time at which the organisation was created'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='source',
            field=models.CharField(default='', help_text='Source from which the organisation has originated', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='callquestion',
            name='answer_max_length',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of words for a question answer', null=True, verbose_name='Answer maximum length (in words)'),
        ),
        migrations.AlterField(
            model_name='callquestion',
            name='question_description',
            field=models.TextField(blank=True, help_text='Explanation of question to enable full completion of answer', null=True),
        ),
        migrations.AlterField(
            model_name='callquestion',
            name='question_text',
            field=models.TextField(help_text='Question text'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='geographical_areas',
            field=models.ManyToManyField(help_text='Geographical area(s) covered by the proposal', to='project_core.GeographicalArea'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='keywords',
            field=models.ManyToManyField(help_text='Keywords that describe the proposal', to='project_core.Keyword'),
        ),
        migrations.AlterField(
            model_name='templatequestion',
            name='answer_max_length',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of words for a question answer', null=True, verbose_name='Answer maximum length (in words)'),
        ),
        migrations.AlterField(
            model_name='templatequestion',
            name='question_description',
            field=models.TextField(blank=True, help_text='Explanation of question to enable full completion of answer', null=True),
        ),
        migrations.AlterField(
            model_name='templatequestion',
            name='question_text',
            field=models.TextField(help_text='Question text'),
        ),
    ]
