# Generated by Django 2.2.6 on 2019-10-14 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0031_import_organisations'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time at which the keyword was created'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='source',
            field=models.CharField(default='', help_text='Source from which the keyword originated', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='source',
            name='source',
            field=models.CharField(help_text='Source from which a UID may originate', max_length=200),
        ),
    ]
