# Generated by Django 2.2.6 on 2019-10-21 09:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0032_add_date_created_source-keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='start_timeframe',
        ),
        migrations.AddField(
            model_name='proposal',
            name='duration_months',
            field=models.DecimalField(decimal_places=1, help_text='Period of time expected that the proposed project will last in months', max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='provisional_end_date',
            field=models.DateField(help_text='Approximate date on which the proposed project is expected to end'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='provisional_start_date',
            field=models.DateField(help_text='Approximate date on which the proposed project is expected to start'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organisation',
            name='source',
            field=models.ForeignKey(help_text='Source from which the organisation has originated', on_delete=django.db.models.deletion.PROTECT, to='project_core.Source'),
        ),
        migrations.AlterField(
            model_name='source',
            name='source',
            field=models.CharField(help_text='Source from which a UID or item may originate', max_length=200),
        ),
    ]
