# Generated by Django 2.2.6 on 2019-10-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0033_proposal_timeframe_chnages'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='eligibility',
            field=models.BooleanField(default=0, help_text='Eligibility status of proposal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='eligibility_comment',
            field=models.TextField(blank=True, help_text='Comments regarding eligibility of proposal', null=True),
        ),
    ]
