# Generated by Django 2.2.6 on 2019-10-21 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_core', '0034_added_proposal_eligibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingInstrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(help_text='Full name of funding instrument', max_length=200)),
                ('short_name', models.CharField(help_text='Short name or acronym of the funding instrument', max_length=60)),
                ('description', models.TextField(help_text='Desription of the funding instrument that can be used to distinguish it from others')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time on which the funding instrument was created')),
                ('date_modified', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Date and time on which the funding instrument was modified', null=True)),
                ('created_by', models.ForeignKey(help_text='User id of person creating the funding instrument', on_delete=django.db.models.deletion.PROTECT, related_name='created_by_set', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(help_text='User id of person modifying the funding instrument', on_delete=django.db.models.deletion.PROTECT, related_name='modified_by_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='call',
            name='funding_instrument',
            field=models.ForeignKey(blank=True, help_text='Funding instrument to which the call belongs', null=True, on_delete=django.db.models.deletion.PROTECT, to='project_core.FundingInstrument'),
        ),
    ]
