# Generated by Django 2.2.6 on 2019-10-21 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0035_added_funding_instrument_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundinginstrument',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User id of person modifying the funding instrument', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_by_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
