# Generated by Django 2.2.6 on 2019-10-21 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_core', '0036_modified_by_nullable_funding_instrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='created_by',
            field=models.ForeignKey(help_text='User id of person creating the call', on_delete=django.db.models.deletion.PROTECT, related_name='call_created_by_set', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='call',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time on which the call was created'),
        ),
        migrations.AddField(
            model_name='call',
            name='date_modified',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Date and time on which the call was modified', null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User id of person modifying the call', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='call_modified_by_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
