# Generated by Django 2.2.6 on 2019-10-21 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0038_createmodify_to_funding_instrument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='call',
            name='date_modified',
        ),
        migrations.AddField(
            model_name='call',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time at which the entry was created'),
        ),
        migrations.AddField(
            model_name='call',
            name='modified_on',
            field=models.DateTimeField(blank=True, help_text='Date and time at which the entry was modified', null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User by which the entry was created', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_core_call_created_by_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='call',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User by which the entry was modified', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_core_call_modified_by_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fundinginstrument',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User by which the entry was created', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_core_fundinginstrument_created_by_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fundinginstrument',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time at which the entry was created'),
        ),
    ]
