# Generated by Django 2.2.6 on 2019-10-21 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_core', '0039_created_by_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='callquestion',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User by which the entry was created', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_core_callquestion_created_by_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='callquestion',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time at which the entry was created'),
        ),
        migrations.AddField(
            model_name='callquestion',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User by which the entry was modified', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_core_callquestion_modified_by_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='callquestion',
            name='modified_on',
            field=models.DateTimeField(blank=True, help_text='Date and time at which the entry was modified', null=True),
        ),
        migrations.AddField(
            model_name='templatequestion',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User by which the entry was created', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_core_templatequestion_created_by_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='templatequestion',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time at which the entry was created'),
        ),
        migrations.AddField(
            model_name='templatequestion',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User by which the entry was modified', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_core_templatequestion_modified_by_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='templatequestion',
            name='modified_on',
            field=models.DateTimeField(blank=True, help_text='Date and time at which the entry was modified', null=True),
        ),
    ]
