# Generated by Django 2.2.6 on 2019-10-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0043_add_sourcekeyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
