# Generated by Django 2.2.6 on 2019-10-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0044_source_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time at which the entry was created'),
        ),
        migrations.AlterField(
            model_name='call',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, help_text='Date and time at which the entry was modified', null=True),
        ),
        migrations.AlterField(
            model_name='callquestion',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time at which the entry was created'),
        ),
        migrations.AlterField(
            model_name='callquestion',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, help_text='Date and time at which the entry was modified', null=True),
        ),
        migrations.AlterField(
            model_name='fundinginstrument',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time at which the entry was created'),
        ),
        migrations.AlterField(
            model_name='fundinginstrument',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, help_text='Date and time at which the entry was modified', null=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time at which the entry was created'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, help_text='Date and time at which the entry was modified', null=True),
        ),
        migrations.AlterField(
            model_name='keywordsource',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time at which the entry was created'),
        ),
        migrations.AlterField(
            model_name='keywordsource',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, help_text='Date and time at which the entry was modified', null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time at which the entry was created'),
        ),
        migrations.AlterField(
            model_name='source',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, help_text='Date and time at which the entry was modified', null=True),
        ),
        migrations.AlterField(
            model_name='templatequestion',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time at which the entry was created'),
        ),
        migrations.AlterField(
            model_name='templatequestion',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, help_text='Date and time at which the entry was modified', null=True),
        ),
    ]
