# Generated by Django 2.2.6 on 2019-10-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0045_created_modified_on_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordsource',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
