# Generated by Django 2.2.6 on 2019-10-22 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0055_createmodify_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callquestion',
            name='date_created',
        ),
    ]
