# Generated by Django 2.2.6 on 2019-10-22 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_core', '0059_createmodify_proposalqatext'),
    ]

    operations = [
        migrations.AddField(
            model_name='callcomment',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User by which the entry was created', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_core_callcomment_created_by_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='callcomment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=None, help_text='Date and time at which the entry was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='callcomment',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User by which the entry was modified', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_core_callcomment_modified_by_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='callcomment',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, help_text='Date and time at which the entry was modified', null=True),
        ),
        migrations.AddField(
            model_name='proposalcomment',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User by which the entry was created', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_core_proposalcomment_created_by_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposalcomment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=None, help_text='Date and time at which the entry was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposalcomment',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User by which the entry was modified', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_core_proposalcomment_modified_by_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposalcomment',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, help_text='Date and time at which the entry was modified', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='callcomment',
            unique_together={('call', 'created_on', 'created_by')},
        ),
        migrations.AlterUniqueTogether(
            name='proposalcomment',
            unique_together={('proposal', 'created_on', 'created_by')},
        ),
        migrations.RemoveField(
            model_name='callcomment',
            name='time',
        ),
        migrations.RemoveField(
            model_name='callcomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='proposalcomment',
            name='time',
        ),
        migrations.RemoveField(
            model_name='proposalcomment',
            name='user',
        ),
    ]
