# Generated by Django 2.2.6 on 2019-10-23 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0062_geographicalareauid_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geographicalarea',
            name='uid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='project_core.GeographicalAreaUid'),
        ),
    ]
