# Generated by Django 2.2.6 on 2019-10-23 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0066_choices_porposal_eligibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='duration_months',
            field=models.DecimalField(decimal_places=1, help_text='Period of time expected that the proposed project will last in months', max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
