# Generated by Django 2.2.6 on 2019-10-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0068_personposition_model_booleans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='description',
            field=models.CharField(blank=True, help_text='Description of a keyword that should be used to distinguish it from another keyword', max_length=512, null=True),
        ),
    ]
