# Generated by Django 2.2.6 on 2019-10-23 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0069_keyword_description_nullable'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='physicalperson',
            unique_together={('first_name', 'surname', 'gender')},
        ),
    ]
