# Generated by Django 2.2.6 on 2019-10-24 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0070_gender_part_of_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callquestion',
            old_name='question',
            new_name='template_question',
        ),
        migrations.AlterUniqueTogether(
            name='callquestion',
            unique_together={('call', 'order'), ('call', 'template_question')},
        ),
    ]
