# Generated by Django 2.2.6 on 2019-10-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0072_call_funding_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='other_funding_question',
            field=models.BooleanField(default=True, help_text='True if the Other Funding question is enabled'),
            preserve_default=False,
        ),
    ]
