# Generated by Django 2.2.6 on 2019-10-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0073_makes_other_funding_mandatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='proposal_partner_question',
            field=models.BooleanField(default=False, help_text='True if the Proposal Partner question is enabled'),
            preserve_default=False,
        ),
    ]
