# Generated by Django 2.2.6 on 2019-10-31 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0074_call_proposal_partner_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetcategory',
            name='order',
            field=models.PositiveIntegerField(default=10, help_text='Use the integer order to order the categories'),
        ),
    ]
