# Generated by Django 2.2.6 on 2019-11-07 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_core', '0076_physical_person_unique_not_including_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callquestion',
            name='answer_max_length',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of words for a question answer', null=True, verbose_name='Answer maximum length (used for answer type TEXT, in words)'),
        ),
        migrations.AlterField(
            model_name='callquestion',
            name='answer_type',
            field=models.CharField(choices=[('Text', 'Text'), ('File', 'File')], default='Text', help_text='Type of field that should be applied to the question answer', max_length=5),
        ),
        migrations.AlterField(
            model_name='templatequestion',
            name='answer_max_length',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of words for a question answer', null=True, verbose_name='Answer maximum length (used for answer type TEXT, in words)'),
        ),
        migrations.AlterField(
            model_name='templatequestion',
            name='answer_type',
            field=models.CharField(choices=[('Text', 'Text'), ('File', 'File')], default='Text', help_text='Type of field that should be applied to the question answer', max_length=5),
        ),
        migrations.CreateModel(
            name='ProposalQAFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date and time at which the entry was created')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Date and time at which the entry was modified', null=True)),
                ('file', models.FileField(upload_to='')),
                ('call_question', models.ForeignKey(help_text='Question from the call', on_delete=django.db.models.deletion.PROTECT, to='project_core.CallQuestion')),
                ('created_by', models.ForeignKey(blank=True, help_text='User by which the entry was created', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_core_proposalqafile_created_by_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, help_text='User by which the entry was modified', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_core_proposalqafile_modified_by_related', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(help_text='Proposal that this file is attached to', on_delete=django.db.models.deletion.PROTECT, to='project_core.Proposal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
