# Generated by Django 2.2.6 on 2019-11-07 14:15

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0077_add_question_files_for_proposals'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalqafile',
            name='md5',
            field=models.CharField(db_index=True, default=None, max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proposalqafile',
            name='file',
            field=models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to='project/proposals_qa/'),
        ),
    ]
