# Generated by Django 2.2.6 on 2019-11-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0077_add_question_files_for_proposals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundinginstrument',
            name='description',
            field=models.TextField(help_text='Description of the funding instrument that can be used to distinguish it from others'),
        ),
    ]
