# Generated by Django 2.2.6 on 2019-11-27 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0080_same_file_attached_twice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='uid',
            field=models.ForeignKey(help_text='UID of an organisation', on_delete=django.db.models.deletion.PROTECT, to='project_core.OrganisationUid'),
        ),
        migrations.AlterField(
            model_name='proposalpartner',
            name='competences',
            field=models.TextField(help_text="Description of the partner's key competences"),
        ),
        migrations.AlterField(
            model_name='proposalpartner',
            name='role',
            field=models.ForeignKey(help_text='Role of the partner', on_delete=django.db.models.deletion.PROTECT, to='project_core.Role'),
        ),
        migrations.AlterField(
            model_name='proposalpartner',
            name='role_description',
            field=models.TextField(help_text="Description of the partner's role"),
        ),
    ]
