# Generated by Django 2.2.6 on 2019-11-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0082_adds_external_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='overarching_project_question',
            field=models.BooleanField(default=False, help_text='True if the question for the overarching project is displayed'),
        ),
    ]
