# Generated by Django 2.2.6 on 2019-11-27 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0083_call_project_overarching_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='overarching_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='project_core.ExternalProject'),
        ),
    ]
