# Generated by Django 2.2.6 on 2019-11-27 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0084_proposal_overarching_project'),
        ('project_core', '0084_career_stage'),
    ]

    operations = [
    ]
