# Generated by Django 2.2.6 on 2019-11-28 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0086_organisationname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personposition',
            name='organisations',
        ),
        migrations.AddField(
            model_name='personposition',
            name='organisation_names',
            field=models.ManyToManyField(help_text='Organisation(s) represented by the person', to='project_core.OrganisationName'),
        ),
        migrations.AddField(
            model_name='proposalfundingitem',
            name='organisation_name',
            field=models.ForeignKey(default='', help_text='Name of organisation from which the funding is sourced', on_delete=django.db.models.deletion.PROTECT, to='project_core.OrganisationName'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='proposalfundingitem',
            unique_together={('organisation_name', 'funding_status', 'proposal', 'amount')},
        ),
        migrations.RemoveField(
            model_name='proposalfundingitem',
            name='organisation',
        ),
    ]
