# Generated by Django 2.2.6 on 2019-11-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0087_uses_organisation_names_for_funding_and_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Postal code of the organisation', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='street',
            field=models.CharField(blank=True, help_text='Street address of the organisation', max_length=500, null=True),
        ),
    ]
