# Generated by Django 2.2.6 on 2019-12-02 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0088_organisation_mandatory_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personposition',
            old_name='data_policy',
            new_name='privacy_policy',
        ),
    ]
