# Generated by Django 2.2.6 on 2019-12-03 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0089_change_data_policy_to_privacy_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='duration_months',
            field=models.DecimalField(decimal_places=1, help_text='Expected duration of the proposed project in months', max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
