# Generated by Django 2.2.6 on 2019-12-04 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0093_careerstage_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalfundingitem',
            name='funding_status',
            field=models.ForeignKey(help_text='Status of the funding', on_delete=django.db.models.deletion.PROTECT, to='project_core.FundingStatus'),
        ),
    ]
