# Generated by Django 2.2.6 on 2019-12-04 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0094_funding_source_helptext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='provisional_start_date',
            new_name='start_date',
        ),
    ]
