# Generated by Django 2.2.6 on 2019-12-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0096_proposal_enddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalperson',
            name='phd_date',
            field=models.CharField(blank=True, help_text='Date (mm/yyyy) on which PhD awarded or expected', max_length=20, null=True),
        ),
    ]
