# Generated by Django 2.2.6 on 2020-01-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0099_proposal_mails_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundinginstrument',
            name='long_name',
            field=models.CharField(help_text='Full name of funding instrument', max_length=200, unique=True),
        ),
    ]
