# Generated by Django 2.2.6 on 2020-02-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0101_auto_20200207_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the colour', max_length=64, unique=True)),
                ('hex_code', models.CharField(help_text='Hex code, e.g. FF0000 for red', max_length=6, unique=True)),
            ],
        ),
    ]
