# Generated by Django 2.2.6 on 2020-02-13 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0017_uses_model_from_colour_application'),
        ('project_core', '0103_colours_are_7_chars'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Colour',
        ),
    ]
