# Generated by Django 3.0.3 on 2020-02-19 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0106_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='allocated_budget',
            field=models.DecimalField(decimal_places=2, help_text='Budget allocated to project', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
