# Generated by Django 3.0.3 on 2020-03-16 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0108_abortion_reason_project'),
        ('project_core', '0108_historicalcallquestion_historicaltemplatequestion'),
    ]

    operations = [
    ]
