# Generated by Django 3.0.3 on 2020-03-16 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0109_merge_20200316_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='project',
            name='modified_by',
        ),
    ]
