# Generated by Django 3.0.3 on 2020-03-17 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0110_removes_createdby_modifiedby_from_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='duration_months',
        ),
    ]
