# Generated by Django 3.0.3 on 2020-03-20 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0111_remove_project_duration_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalphysicalperson',
            name='orcid_id',
            field=models.CharField(help_text='Orcid ID', max_length=19, null=True, validators=[django.core.validators.RegexValidator(code='Invalid format', message='Format orcid ID is 0000-0000-0000-0000', regex='^[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{4}$')]),
        ),
        migrations.AddField(
            model_name='physicalperson',
            name='orcid_id',
            field=models.CharField(help_text='Orcid ID', max_length=19, null=True, validators=[django.core.validators.RegexValidator(code='Invalid format', message='Format orcid ID is 0000-0000-0000-0000', regex='^[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{4}$')]),
        ),
    ]
