# Generated by Django 3.0.3 on 2020-04-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0115_historicalproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundinginstrument',
            name='short_name',
            field=models.CharField(help_text='Short name or acronym of the funding instrument', max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalfundinginstrument',
            name='short_name',
            field=models.CharField(db_index=True, help_text='Short name or acronym of the funding instrument', max_length=60),
        ),
    ]
