# Generated by Django 3.0.3 on 2020-04-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0116_makes_funding_instrument_short_name_not_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='finance_year',
            field=models.IntegerField(default=2020, help_text='Finance year of this call. It is used, for example, for the project key from this call'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcall',
            name='finance_year',
            field=models.IntegerField(default=2020, help_text='Finance year of this call. It is used, for example, for the project key from this call'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='key',
            field=models.CharField(db_index=True, default='', help_text='Project key identifier all the way to finance', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='key',
            field=models.CharField(default='', help_text='Project key identifier all the way to finance', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
