# Generated by Django 3.0.3 on 2020-04-02 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0117_add_call_finance_year_and_project_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='funding_instrument',
            field=models.ForeignKey(help_text='Funding instrument to which the call belongs', on_delete=django.db.models.deletion.PROTECT, to='project_core.FundingInstrument'),
        ),
    ]
