# Generated by Django 3.0.5 on 2020-05-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0119_financialkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialkey',
            name='name',
            field=models.CharField(help_text='Code used by finance (e.g. ECON, TRAVEL) or funding instrument', max_length=20, unique=True),
        ),
    ]
