# Generated by Django 3.0.5 on 2020-05-20 15:05

from django.db import migrations, models

def copy_financial_instrument_short_names_to_temp(apps, schema_editor):
    FundingInstrument = apps.get_model('project_core', 'FundingInstrument')

    for funding_instrument in FundingInstrument.objects.all():
        funding_instrument.short_name_temp = funding_instrument.short_name
        funding_instrument.save()


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0120_financial_key_name_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundinginstrument',
            name='short_name_temp',
            field=models.CharField(default=None, help_text='Short name or acronym of the funding instrument', max_length=60, unique=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalfundinginstrument',
            name='short_name_temp',
            field=models.CharField(db_index=True, default=None, help_text='Short name or acronym of the funding instrument', max_length=60),
            preserve_default=False,
        ),
        migrations.RunPython(copy_financial_instrument_short_names_to_temp),
    ]
