# Generated by Django 3.0.5 on 2020-05-20 15:09

import django.db.models.deletion
from django.db import migrations, models


def create_financial_keys(apps, schema_editor):
    FundingInstrument = apps.get_model('project_core', 'FundingInstrument')
    FinancialKey = apps.get_model('project_core', 'FinancialKey')
    User = apps.get_model('auth', 'User')

    admin_user = User.objects.get(username='admin')

    print('here01')
    for funding_instrument in FundingInstrument.objects.all():
        print(funding_instrument)
        financial_key, created = FinancialKey.objects.get_or_create(name=funding_instrument.short_name,
                                                                    defaults={
                                                                        'description': 'Automatically migrated from FundingInstrument',
                                                                        'created_by': admin_user})
        print('here02')
        funding_instrument.short_name = financial_key.id
        funding_instrument.save()

    HistoricalFundingInstrumentHistorical = apps.get_model('project_core', 'HistoricalFundingInstrument')
    HistoricalFundingInstrumentHistorical.objects.all().delete()

class Migration(migrations.Migration):
    dependencies = [
        ('project_core', '0121_funding_instrument_short_name_temp_column'),
    ]

    operations = [
        migrations.RunPython(create_financial_keys),

        migrations.AlterField(
            model_name='fundinginstrument',
            name='short_name',
            field=models.OneToOneField(help_text='Short name or acronym of the funding instrument', null=True,
                                       on_delete=django.db.models.deletion.PROTECT, to='project_core.FinancialKey'),
        ),
        migrations.AlterField(
            model_name='historicalfundinginstrument',
            name='short_name',
            field=models.ForeignKey(blank=True, db_constraint=False,
                                    help_text='Short name or acronym of the funding instrument', null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='project_core.FinancialKey'),
        ),
    ]
