# Generated by Django 3.0.5 on 2020-05-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0123_funding_instrument_delete_short_name_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialkey',
            name='funding_instrument',
            field=models.BooleanField(default=True, help_text='This field is booked or used for a funding instrument'),
        ),
    ]
