# Generated by Django 3.0.7 on 2020-07-06 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0127_allocated_budget_project_status_default_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='supervisor',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Supervisor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project_core.PersonPosition'),
        ),
        migrations.AddField(
            model_name='project',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Supervisor', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supervisor', to='project_core.PersonPosition'),
        ),
    ]
