# Generated by Django 3.0.5 on 2020-07-29 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0128_add_supervisor_for_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personposition',
            options={},
        ),
    ]
