# Generated by Django 3.0.8 on 2020-07-30 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0129_person_position_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostalAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date and time at which the entry was created')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Date and time at which the entry was modified', null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=256)),
                ('postcode', models.CharField(max_length=128)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project_core.Country')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
