# Generated by Django 3.0.8 on 2020-08-14 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0133_auto_add_head_of_research_unit_in_proposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date and time at which the entry was created')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Date and time at which the entry was modified', null=True)),
                ('description', models.TextField(help_text='Description of the role')),
                ('competences', models.TextField(help_text='Description of the key competences')),
                ('role', models.ForeignKey(help_text='Role of the partner', on_delete=django.db.models.deletion.PROTECT, to='project_core.Role')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='historicalproposal',
            name='applicant_role_description',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Main applicant role', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project_core.RoleDescription'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='applicant_role_description',
            field=models.ForeignKey(blank=True, help_text='Main applicant role', null=True, on_delete=django.db.models.deletion.PROTECT, to='project_core.RoleDescription'),
        ),
    ]
