# Generated by Django 3.0.10 on 2020-09-28 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0138_add_file_validator'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCategoryCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date and time at which the entry was created')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Date and time at which the entry was modified', null=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('budget_category', models.ForeignKey(help_text='Budget category for this category', on_delete=django.db.models.deletion.PROTECT, to='project_core.BudgetCategory')),
                ('call', models.ForeignKey(help_text='Call where this category is used in', on_delete=django.db.models.deletion.PROTECT, to='project_core.Call')),
            ],
            options={
                'unique_together': {('call', 'budget_category')},
            },
        ),
    ]
