# Generated by Django 3.0.10 on 2020-09-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0140_created_sorted_budget_category_call'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='budget_categories',
        ),
        migrations.AddField(
            model_name='budgetcategorycall',
            name='enabled',
            field=models.BooleanField(default=False, help_text='Appears in the proposal form'),
            preserve_default=False,
        ),
    ]
