# Generated by Django 3.0.10 on 2020-10-05 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0140_migrate_budget_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproposal',
            name='duration_months',
            field=models.DecimalField(decimal_places=2, help_text='Expected duration of the proposed project in months', max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='duration_months',
            field=models.DecimalField(decimal_places=2, help_text='Expected duration of the proposed project in months', max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
