# Generated by Django 3.0.10 on 2020-10-23 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0141_project_duration_two_decimals'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='physicalperson',
            options={'verbose_name_plural': 'Physical People'},
        ),
    ]
