# Generated by Django 3.0.10 on 2020-09-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0141_add_budget_category_call_enabled_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetcategorycall',
            name='enabled',
            field=models.BooleanField(default=False, help_text='Appears in the proposal form'),
        ),
    ]
