# Generated by Django 3.0.10 on 2020-11-12 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0142_fix_physicalperson_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalScientificCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date and time at which the entry was created')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Date and time at which the entry was modified', null=True)),
                ('title', models.CharField(help_text='Title of the scientific cluster', max_length=500)),
                ('applicant', models.ForeignKey(help_text='Main applicant of the proposal', on_delete=django.db.models.deletion.PROTECT, to='project_core.PersonPosition')),
                ('keywords', models.ManyToManyField(help_text='Keywords that describe the scientific cluster', to='project_core.Keyword')),
                ('proposal', models.ForeignKey(help_text='Proposal that this Scientific Cluster refers to', on_delete=django.db.models.deletion.PROTECT, to='project_core.Proposal')),
            ],
            options={
                'unique_together': {('title', 'proposal')},
            },
        ),
    ]
