# Generated by Django 3.0.10 on 2020-11-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0143_proposalscientificcluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='scientific_cluster_question',
            field=models.BooleanField(default=False, help_text='True if the Scientific Cluster question is enabled'),
        ),
        migrations.AddField(
            model_name='historicalcall',
            name='scientific_cluster_question',
            field=models.BooleanField(default=False, help_text='True if the Scientific Cluster question is enabled'),
        ),
    ]
