# Generated by Django 3.0.10 on 2020-11-12 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0144_call'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='scientific_cluster_question',
            new_name='scientific_clusters_question',
        ),
        migrations.RenameField(
            model_name='historicalcall',
            old_name='scientific_cluster_question',
            new_name='scientific_clusters_question',
        ),
    ]
