# Generated by Django 3.0.10 on 2020-12-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0146_delete_create_scientificcluster_sub_pi'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='keywords_in_general_information_question',
            field=models.NullBooleanField(default=True, help_text='True if we want to ask the keywords in the general section'),
        ),
        migrations.AddField(
            model_name='historicalcall',
            name='keywords_in_general_information_question',
            field=models.NullBooleanField(default=True, help_text='True if we want to ask the keywords in the general section'),
        ),
    ]
