# Generated by Django 3.0.10 on 2020-12-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0147_add_field_to_enable_disable_keywords_question_general_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='keywords_in_general_information_question',
            field=models.BooleanField(default=True, help_text='True if we want to ask the keywords in the general section'),
        ),
        migrations.AlterField(
            model_name='historicalcall',
            name='keywords_in_general_information_question',
            field=models.BooleanField(default=True, help_text='True if we want to ask the keywords in the general section'),
        ),
    ]
