# Generated by Django 3.1.4 on 2020-12-14 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0148_make_keywords_in_general_information_question_mandatory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date and time at which the entry was created')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Date and time at which the entry was modified', null=True)),
                ('title', models.CharField(max_length=500)),
                ('introductory_text', models.TextField()),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('call', models.ForeignKey(help_text='Call that this ProposalPart belongs to', on_delete=django.db.models.deletion.PROTECT, to='project_core.call')),
            ],
            options={
                'unique_together': {('call', 'order'), ('call', 'title')},
            },
        ),
    ]
