# Generated by Django 3.1.4 on 2020-12-21 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0149_callpart'),
    ]

    operations = [
        migrations.AddField(
            model_name='callquestion',
            name='call_part',
            field=models.ForeignKey(help_text='To which Call Part this question belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='project_core.callpart'),
        ),
        migrations.AddField(
            model_name='historicalcallquestion',
            name='call_part',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='To which Call Part this question belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project_core.callpart'),
        ),
    ]
