# Generated by Django 3.1.4 on 2020-12-21 14:46

from django.db import migrations

from ProjectApplication import settings


def create_default_part(apps, schema_editor):
    CallPart = apps.get_model('project_core', 'CallPart')
    Call = apps.get_model('project_core', 'Call')

    for call in Call.objects.all():
        # It assumes the database should not have any order=1 Part for this call
        call_part = CallPart.objects.create(call=call, title=settings.CALL_DEFAULT_PART_QUESTIONS_ANSWERS, order=1)

        for call_question in call.callquestion_set.all():
            call_question.call_part = call_part
            call_question.save()


class Migration(migrations.Migration):
    dependencies = [
        ('project_core', '0151_add_call_part_into_call_question'),
    ]

    operations = [
        migrations.RunPython(create_default_part),
    ]
