# Generated by Django 3.1.4 on 2020-12-23 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0152_create_default_part'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcallquestion',
            name='call',
        ),
        migrations.AlterField(
            model_name='callquestion',
            name='call_part',
            field=models.ForeignKey(default=1, help_text='To which Call Part this question belongs to', on_delete=django.db.models.deletion.PROTECT, to='project_core.callpart'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='callpart',
            unique_together={('call', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='callquestion',
            unique_together={('call_part', 'order'), ('call_part', 'template_question')},
        ),
        migrations.RemoveField(
            model_name='callquestion',
            name='call',
        ),
    ]
