# Generated by Django 3.1.4 on 2021-01-05 15:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import project_core.models
import project_core.utils.utils
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0153_auto_20201223_call_question_call_parts'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallPartFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date and time at which the entry was created')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Date and time at which the entry was modified', null=True)),
                ('name', models.CharField(help_text='Name of the file', max_length=64)),
                ('description', models.CharField(help_text='Description of this file', max_length=512)),
                ('file', models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=project_core.models.call_part_file_rename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'jpg', 'jpeg', 'png']), project_core.utils.utils.file_size_validator])),
                ('call_part', models.ForeignKey(help_text='Call part that this file belongs to', on_delete=django.db.models.deletion.PROTECT, to='project_core.callpart')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
