# Generated by Django 3.1.4 on 2021-01-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0154_callpartfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='callpartfile',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='callpartfile',
            unique_together={('call_part', 'name')},
        ),
    ]
