# Generated by Django 3.1.4 on 2021-01-06 15:13

import django.core.validators
from django.db import migrations, models
import project_core.models
import project_core.utils.SpiS3Boto3Storage
import project_core.utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0155_unique_indices_call_part_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='request_overall_budget',
            field=models.BooleanField(default=False, help_text='True to add the question "Requested overall budget". Useful to request a bulk number instead of the budget breakdown. Budget breakdown is displayed/hidden depending on the categories checked in its section'),
        ),
        migrations.AddField(
            model_name='historicalcall',
            name='request_overall_budget',
            field=models.BooleanField(default=False, help_text='True to add the question "Requested overall budget". Useful to request a bulk number instead of the budget breakdown. Budget breakdown is displayed/hidden depending on the categories checked in its section'),
        ),
        migrations.AlterField(
            model_name='callpartfile',
            name='file',
            field=models.FileField(storage=project_core.utils.SpiS3Boto3Storage.SpiS3Boto3Storage(), upload_to=project_core.models.call_part_file_rename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'jpg', 'jpeg', 'png']), project_core.utils.utils.file_size_validator]),
        ),
    ]
