# Generated by Django 3.1.4 on 2021-01-06 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0156_proposal_add_field_request_overall_budget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='request_overall_budget',
            new_name='request_overall_budget_question',
        ),
        migrations.RenameField(
            model_name='historicalcall',
            old_name='request_overall_budget',
            new_name='request_overall_budget_question',
        ),
    ]
