# Generated by Django 3.1.4 on 2021-01-06 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0157_call_request_overall_budget_question_rename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='request_overall_budget_question',
            new_name='overall_budget_question',
        ),
        migrations.RenameField(
            model_name='historicalcall',
            old_name='request_overall_budget_question',
            new_name='overall_budget_question',
        ),
        migrations.AddField(
            model_name='historicalproposal',
            name='overall_budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='If Call.overall_budget_question is enabled it contains the overall budget. It should be used only if no Budget Categories', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='proposal',
            name='overall_budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='If Call.overall_budget_question is enabled it contains the overall budget. It should be used only if no Budget Categories', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
