# Generated by Django 3.1.5 on 2021-01-11 11:33

import django.core.validators
from django.db import migrations, models
import project_core.models
import project_core.utils.SpiS3Boto3Storage
import project_core.utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0158_call_overall_budget_question_rename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callpart',
            name='introductory_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='callpartfile',
            name='file',
            field=models.FileField(storage=project_core.utils.SpiS3Boto3Storage.SpiS3Boto3Storage(), upload_to=project_core.models.call_part_file_rename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'odt', 'jpg', 'jpeg', 'png']), project_core.utils.utils.file_size_validator]),
        ),
    ]
