# Generated by Django 3.1.5 on 2021-01-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0159_call_part_introductory_text_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalscientificcluster',
            name='title',
            field=models.CharField(help_text='Title of the scientific cluster', max_length=500),
        ),
    ]
