# Generated by Django 3.1.5 on 2021-01-11 17:12

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0160_reduce_size_title_abstract_scientific_cluster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callpartfile',
            name='name',
            field=models.CharField(help_text='Name of the file', max_length=64, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')]),
        ),
    ]
