# Generated by Django 3.2 on 2021-04-23 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0162_callpartfile_proposal_keywords_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialkey',
            name='account_number',
            field=models.IntegerField(help_text='Code use by the accounting department', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='scientific_clusters_question',
            field=models.BooleanField(default=False, help_text='True if the Research Cluster question is enabled'),
        ),
        migrations.AlterField(
            model_name='historicalcall',
            name='scientific_clusters_question',
            field=models.BooleanField(default=False, help_text='True if the Research Cluster question is enabled'),
        ),
        migrations.AlterField(
            model_name='proposalscientificcluster',
            name='keywords',
            field=models.ManyToManyField(help_text='Keywords that describe the research cluster', to='project_core.Keyword'),
        ),
        migrations.AlterField(
            model_name='proposalscientificcluster',
            name='proposal',
            field=models.ForeignKey(help_text='Proposal that this Research Cluster refers to', on_delete=django.db.models.deletion.PROTECT, to='project_core.proposal'),
        ),
        migrations.AlterField(
            model_name='proposalscientificcluster',
            name='sub_pi',
            field=models.ForeignKey(help_text='Main person of this research cluster', on_delete=django.db.models.deletion.PROTECT, to='project_core.personposition'),
        ),
        migrations.AlterField(
            model_name='proposalscientificcluster',
            name='title',
            field=models.CharField(help_text='Title of the research cluster', max_length=500),
        ),
    ]
