# Generated by Django 3.2 on 2021-05-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0164_callcareerstage'),
    ]

    operations = [
        migrations.AddField(
            model_name='callcareerstage',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
