# Generated by Django 3.2.3 on 2021-06-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0166_organisation_long_name_english'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='long_name_english',
        ),
        migrations.AddField(
            model_name='organisation',
            name='display_name',
            field=models.CharField(blank=True, help_text='Name of organisation used for display purposes', max_length=100, null=True),
        ),
    ]
