# Generated by Django 3.2.3 on 2021-11-11 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0167_organisation_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='funding_instrument',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Funding instrument to which the call belongs', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project_core.fundinginstrument'),
        ),
        migrations.AddField(
            model_name='project',
            name='funding_instrument',
            field=models.ForeignKey(blank=True, help_text='Funding instrument to which the call belongs', null=True, on_delete=django.db.models.deletion.PROTECT, to='project_core.fundinginstrument'),
        ),
    ]
