# Generated by Django 3.2.3 on 2021-11-11 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0168_add_funding_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='funding_instrument',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Funding instrument to which the project belongs', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project_core.fundinginstrument'),
        ),
        migrations.AlterField(
            model_name='project',
            name='funding_instrument',
            field=models.ForeignKey(help_text='Funding instrument to which the project belongs', on_delete=django.db.models.deletion.PROTECT, to='project_core.fundinginstrument'),
        ),
    ]
