# Generated by Django 3.2.3 on 2021-11-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0170_add_project_finance_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='finance_year',
            field=models.IntegerField(help_text='Finance year of this project',
                                      null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='finance_year',
            field=models.IntegerField(help_text='Finance year of this project'),
        ),
    ]
