# Generated by Django 3.2.3 on 2021-11-12 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0171_make_project_finance_year_not_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='finance_year',
            field=models.IntegerField(default=0, help_text='Finance year of this project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='call',
            field=models.ForeignKey(blank=True, help_text='Call to which the project belongs', null=True, on_delete=django.db.models.deletion.PROTECT, to='project_core.call'),
        ),
    ]
