# Generated by Django 3.2.9 on 2021-12-03 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_core', '0174_spiuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='closed_on',
            field=models.DateTimeField(blank=True, help_text='When the project was closed', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='closed_on',
            field=models.DateTimeField(blank=True, help_text='When the project was closed', null=True),
        ),
    ]
