# Generated by Django 3.2.13 on 2022-07-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0177_add_on_webite_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='on_website',
            field=models.BooleanField(default=False, help_text='Appears in the website'),
        ),
        migrations.AlterField(
            model_name='project',
            name='on_website',
            field=models.BooleanField(default=False, help_text='Appears in the website'),
        ),
    ]
