# Generated by Django 3.2.23 on 2024-06-12 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0182_auto_20240522_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproposal',
            name='duration_months',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected duration of the proposed project in months', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproposal',
            name='eligibility',
            field=models.CharField(blank=True, choices=[('Eligibility not checked', 'Eligibility not checked'), ('Eligible', 'Eligible'), ('Not eligible', 'Not eligible')], default='Eligibility not checked', help_text='Status of eligibility of proposal', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproposal',
            name='end_date',
            field=models.DateField(blank=True, help_text='Approximate date on which the proposed project is expected to end', null=True),
        ),
        migrations.AlterField(
            model_name='historicalproposal',
            name='start_date',
            field=models.DateField(blank=True, help_text='Approximate date on which the proposed project is expected to start', null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='applicant',
            field=models.ForeignKey(blank=True, help_text='Main applicant of the proposal', null=True, on_delete=django.db.models.deletion.PROTECT, to='project_core.personposition'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='call',
            field=models.ForeignKey(blank=True, help_text='Call to which the proposal relates', null=True, on_delete=django.db.models.deletion.PROTECT, to='project_core.call'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='duration_months',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected duration of the proposed project in months', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='eligibility',
            field=models.CharField(blank=True, choices=[('Eligibility not checked', 'Eligibility not checked'), ('Eligible', 'Eligible'), ('Not eligible', 'Not eligible')], default='Eligibility not checked', help_text='Status of eligibility of proposal', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='end_date',
            field=models.DateField(blank=True, help_text='Approximate date on which the proposed project is expected to end', null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='geographical_areas',
            field=models.ManyToManyField(blank=True, help_text='Geographical area(s) covered by the proposal', null=True, to='project_core.GeographicalArea'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='keywords',
            field=models.ManyToManyField(blank=True, help_text='Keywords that describe the proposal', null=True, to='project_core.Keyword'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='start_date',
            field=models.DateField(blank=True, help_text='Approximate date on which the proposed project is expected to start', null=True),
        ),
    ]
