# Generated by Django 3.2.23 on 2024-06-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0183_auto_20240612_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpersonposition',
            name='privacy_policy',
            field=models.BooleanField(blank=True, default=False, help_text='Agree or disagree to the data policy for storage of personal information', null=True),
        ),
        migrations.AlterField(
            model_name='personposition',
            name='privacy_policy',
            field=models.BooleanField(blank=True, default=False, help_text='Agree or disagree to the data policy for storage of personal information', null=True),
        ),
    ]
