# Generated by Django 3.2.23 on 2024-06-14 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0184_auto_20240613_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproposal',
            name='title',
            field=models.CharField(blank=True, help_text='Title of the proposal being submitted', max_length=500),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='geographical_areas',
            field=models.ManyToManyField(blank=True, help_text='Geographical area(s) covered by the proposal', to='project_core.GeographicalArea'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='keywords',
            field=models.ManyToManyField(blank=True, help_text='Keywords that describe the proposal', to='project_core.Keyword'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='postal_address',
            field=models.ForeignKey(blank=True, help_text='Address to where the grant agreement is going to be sent', null=True, on_delete=django.db.models.deletion.PROTECT, to='project_core.postaladdress'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='proposal_status',
            field=models.ForeignKey(blank=True, help_text='Status or outcome of the proposal', null=True, on_delete=django.db.models.deletion.PROTECT, to='project_core.proposalstatus'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='title',
            field=models.CharField(blank=True, help_text='Title of the proposal being submitted', max_length=500),
        ),
    ]
