# Generated by Django 3.2.23 on 2024-06-19 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0185_auto_20240614_0629'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proposal',
            unique_together=set(),
        ),
    ]
