# Generated by Django 3.2.23 on 2024-06-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0186_alter_proposal_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproposal',
            name='title',
            field=models.CharField(blank=True, help_text='Title of the proposal being submitted', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='geographical_areas',
            field=models.ManyToManyField(blank=True, help_text='Geographical area(s) covered by the proposal', null=True, to='project_core.GeographicalArea'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='keywords',
            field=models.ManyToManyField(blank=True, help_text='Keywords that describe the proposal', null=True, to='project_core.Keyword'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='title',
            field=models.CharField(blank=True, help_text='Title of the proposal being submitted', max_length=500, null=True),
        ),
    ]
