# Generated by Django 3.2.23 on 2024-06-21 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0188_alter_personposition_academic_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalfundingitem',
            name='funding_status',
            field=models.ForeignKey(blank=True, help_text='Status of the funding', null=True, on_delete=django.db.models.deletion.PROTECT, to='project_core.fundingstatus'),
        ),
    ]
