# Generated by Django 3.2.23 on 2024-06-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0189_alter_proposalfundingitem_funding_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='geographical_areas',
            field=models.ManyToManyField(blank=True, help_text='Geographical area(s) covered by the proposal', to='project_core.GeographicalArea'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='keywords',
            field=models.ManyToManyField(blank=True, help_text='Keywords that describe the proposal', to='project_core.Keyword'),
        ),
    ]
