# Generated by Django 3.2.23 on 2024-07-02 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0190_auto_20240625_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpartner',
            name='competences',
            field=models.TextField(blank=True, help_text="Description of the partner's key competences", null=True),
        ),
        migrations.AlterField(
            model_name='projectpartner',
            name='person',
            field=models.ForeignKey(blank=True, help_text='Person that is a partner', null=True, on_delete=django.db.models.deletion.PROTECT, to='project_core.personposition'),
        ),
        migrations.AlterField(
            model_name='projectpartner',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Role of the partner', null=True, on_delete=django.db.models.deletion.PROTECT, to='project_core.role'),
        ),
        migrations.AlterField(
            model_name='projectpartner',
            name='role_description',
            field=models.TextField(blank=True, help_text="Description of the partner's role", null=True),
        ),
        migrations.AlterField(
            model_name='proposalpartner',
            name='competences',
            field=models.TextField(blank=True, help_text="Description of the partner's key competences", null=True),
        ),
        migrations.AlterField(
            model_name='proposalpartner',
            name='person',
            field=models.ForeignKey(blank=True, help_text='Person that is a partner', null=True, on_delete=django.db.models.deletion.PROTECT, to='project_core.personposition'),
        ),
        migrations.AlterField(
            model_name='proposalpartner',
            name='proposal',
            field=models.ForeignKey(blank=True, help_text='Proposal to on which the partner is collaborating', null=True, on_delete=django.db.models.deletion.PROTECT, to='project_core.proposal'),
        ),
        migrations.AlterField(
            model_name='proposalpartner',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Role of the partner', null=True, on_delete=django.db.models.deletion.PROTECT, to='project_core.role'),
        ),
        migrations.AlterField(
            model_name='proposalpartner',
            name='role_description',
            field=models.TextField(blank=True, help_text="Description of the partner's role", null=True),
        ),
        migrations.AlterField(
            model_name='proposalscientificcluster',
            name='proposal',
            field=models.ForeignKey(blank=True, help_text='Proposal that this Research Cluster refers to', null=True, on_delete=django.db.models.deletion.PROTECT, to='project_core.proposal'),
        ),
    ]
