# Generated by Django 3.2.23 on 2024-07-04 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0191_auto_20240702_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roledescription',
            name='competences',
            field=models.TextField(blank=True, help_text='Description of the key competences', null=True),
        ),
        migrations.AlterField(
            model_name='roledescription',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the role', null=True),
        ),
        migrations.AlterField(
            model_name='roledescription',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Role of the partner', null=True, on_delete=django.db.models.deletion.PROTECT, to='project_core.role'),
        ),
    ]
