# Generated by Django 3.2.23 on 2024-11-29 05:18

import django.core.validators
from django.db import migrations, models
import project_core.models
import project_core.utils.SpiS3Boto3Storage
import project_core.utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0192_auto_20240704_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callpartfile',
            name='file',
            field=models.FileField(storage=project_core.utils.SpiS3Boto3Storage.SpiS3Boto3Storage(), upload_to=project_core.models.call_part_file_rename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'odt', 'jpg', 'jpeg', 'png', 'xlsx', 'xls']), project_core.utils.utils.file_size_validator]),
        ),
    ]
