# Generated by Django 3.0.3 on 2020-04-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laysummary',
            old_name='webversion',
            new_name='web_version',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='urls',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='date_published',
        ),
        migrations.AddField(
            model_name='publication',
            name='date_time_published',
            field=models.DateTimeField(blank=True, help_text='Date of the publication', null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='url',
            field=models.URLField(blank=True, help_text='Web address for entry', null=True),
        ),
        migrations.AlterField(
            model_name='financereport',
            name='due_date',
            field=models.DateField(blank=True, help_text='Date that the document is expected to be received', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total of the invoice (CHF)', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, help_text='Date that the document is expected to be received', null=True),
        ),
        migrations.AlterField(
            model_name='laysummary',
            name='due_date',
            field=models.DateField(blank=True, help_text='Date that the document is expected to be received', null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='due_date',
            field=models.DateField(blank=True, help_text='Date that the document is expected to be received', null=True),
        ),
        migrations.AlterField(
            model_name='projectsocialmedia',
            name='url',
            field=models.URLField(blank=True, help_text='Web address of social media entry', null=True),
        ),
    ]
