# Generated by Django 3.0.3 on 2020-04-07 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grant_management', '0003_remove_socialnetwork_identifier'),
        ('grant_management', '0002_auto_20200406_1008'),
    ]

    operations = [
    ]
