# Generated by Django 3.0.3 on 2020-04-10 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0118_calls_need_to_be_part_of_a_funding_instrument'),
        ('grant_management', '0006_make_sent_date_reception_date_optional'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FinanceReport',
            new_name='FinancialReport',
        ),
    ]
