# Generated by Django 3.0.3 on 2020-04-10 09:59

from django.db import migrations, models
import grant_management.models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('grant_management', '0007_rename_financereport_to_financialreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialreport',
            name='file',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=grant_management.models.finance_report_file_rename),
        ),
    ]
