# Generated by Django 3.0.3 on 2020-04-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant_management', '0008_makes_financial_report_file_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialreport',
            name='sent_for_approval_date',
            field=models.DateField(blank=True, help_text='Date that the finance report was sent for approval', null=True),
        ),
    ]
