# Generated by Django 3.0.3 on 2020-04-10 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0118_calls_need_to_be_part_of_a_funding_instrument'),
        ('grant_management', '0009_makes_sent_for_approval_date_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialreport',
            name='signed_by',
            field=models.ForeignKey(blank=True, help_text='Person who signed the finance report', null=True, on_delete=django.db.models.deletion.PROTECT, to='project_core.PhysicalPerson'),
        ),
    ]
