# Generated by Django 3.0.3 on 2020-04-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant_management', '0011_change_financial_report_date_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialreport',
            name='due_date',
            field=models.DateField(help_text='Date that the document is expected to be received'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(help_text='Date that the document is expected to be received'),
        ),
        migrations.AlterField(
            model_name='laysummary',
            name='due_date',
            field=models.DateField(help_text='Date that the document is expected to be received'),
        ),
        migrations.AlterField(
            model_name='media',
            name='due_date',
            field=models.DateField(help_text='Date that the document is expected to be received'),
        ),
    ]
