# Generated by Django 3.0.5 on 2020-04-16 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0118_calls_need_to_be_part_of_a_funding_instrument'),
        ('grant_management', '0012_makes_due_date_mandatory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialreport',
            name='approval_date',
            field=models.DateField(blank=True, help_text='Date the finance report was approved', null=True),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='due_date',
            field=models.DateField(help_text='Date the document is expected to be received'),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='reception_date',
            field=models.DateField(blank=True, help_text='Date the document was received', null=True),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='sent_date',
            field=models.DateField(blank=True, help_text='Date the document was sent', null=True),
        ),
        migrations.AlterField(
            model_name='grantagreement',
            name='project',
            field=models.OneToOneField(help_text='Project this Grant Agreement belongs to', on_delete=django.db.models.deletion.PROTECT, to='project_core.Project'),
        ),
        migrations.AlterField(
            model_name='grantagreement',
            name='signed_date',
            field=models.DateField(blank=True, help_text='Date the grant agreement was signed', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(help_text='Date the document is expected to be received'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid_date',
            field=models.DateField(blank=True, help_text='Date the invoice was paid', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='reception_date',
            field=models.DateField(blank=True, help_text='Date the document was received', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sent_date',
            field=models.DateField(blank=True, help_text='Date the document was sent', null=True),
        ),
        migrations.AlterField(
            model_name='laysummary',
            name='due_date',
            field=models.DateField(help_text='Date the document is expected to be received'),
        ),
        migrations.AlterField(
            model_name='laysummary',
            name='reception_date',
            field=models.DateField(blank=True, help_text='Date the document was received', null=True),
        ),
        migrations.AlterField(
            model_name='laysummary',
            name='sent_date',
            field=models.DateField(blank=True, help_text='Date the document was sent', null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='due_date',
            field=models.DateField(help_text='Date the document is expected to be received'),
        ),
        migrations.AlterField(
            model_name='media',
            name='reception_date',
            field=models.DateField(blank=True, help_text='Date the document was received', null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='sent_date',
            field=models.DateField(blank=True, help_text='Date the document was sent', null=True),
        ),
    ]
