# Generated by Django 3.0.5 on 2020-04-29 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0118_calls_need_to_be_part_of_a_funding_instrument'),
        ('grant_management', '0015_add_lay_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='reception_date',
        ),
        migrations.RemoveField(
            model_name='media',
            name='sent_date',
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='reception_date',
            field=models.DateField(blank=True, help_text='Date the financial report was received', null=True),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='sent_date',
            field=models.DateField(blank=True, help_text='Date the financial report was sent to review', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='reception_date',
            field=models.DateField(blank=True, help_text='Date the invoice was received', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sent_date',
            field=models.DateField(blank=True, help_text='Date the invoice was sent for payment', null=True),
        ),
        migrations.AlterField(
            model_name='laysummary',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Person who entered this summary', null=True, on_delete=django.db.models.deletion.PROTECT, to='project_core.PhysicalPerson'),
        ),
        migrations.AlterField(
            model_name='laysummary',
            name='reception_date',
            field=models.DateField(blank=True, help_text='Date the Lay Summary was received', null=True),
        ),
        migrations.AlterField(
            model_name='laysummary',
            name='sent_date',
            field=models.DateField(blank=True, help_text='Date the Lay Summary was sent', null=True),
        ),
    ]
