# Generated by Django 3.0.5 on 2020-04-29 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grant_management', '0016_new_dates_handling'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialreport',
            old_name='reception_date',
            new_name='received_date',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='reception_date',
            new_name='received_date',
        ),
        migrations.RenameField(
            model_name='laysummary',
            old_name='reception_date',
            new_name='received_date',
        ),
    ]
