# Generated by Django 3.0.5 on 2020-04-29 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grant_management', '0017_renames_reception_to_received'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laysummary',
            name='sent_date',
        ),
    ]
