# Generated by Django 3.0.5 on 2020-04-29 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0118_calls_need_to_be_part_of_a_funding_instrument'),
        ('grant_management', '0019_add_blog_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialreport',
            name='approval_date',
            field=models.DateField(blank=True, help_text='Date the report was approved', null=True),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Person who signed the report', null=True, on_delete=django.db.models.deletion.PROTECT, to='project_core.PhysicalPerson'),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='received_date',
            field=models.DateField(blank=True, help_text='Date the report was received', null=True),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='sent_date',
            field=models.DateField(blank=True, help_text='Date the report was sent to review', null=True),
        ),
    ]
