# Generated by Django 3.0.5 on 2020-04-29 15:36

from django.db import migrations, models
import django.db.models.deletion
import grant_management.models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0118_calls_need_to_be_part_of_a_funding_instrument'),
        ('grant_management', '0020_uses_abstract_project_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScientificReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date and time at which the entry was created')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Date and time at which the entry was modified', null=True)),
                ('due_date', models.DateField(help_text='Date the document is expected to be received')),
                ('received_date', models.DateField(blank=True, help_text='Date the report was received', null=True)),
                ('sent_date', models.DateField(blank=True, help_text='Date the report was sent to review', null=True)),
                ('approval_date', models.DateField(blank=True, help_text='Date the report was approved', null=True)),
                ('file', models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=grant_management.models.scientific_report_file_rename)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Person who signed the report', null=True, on_delete=django.db.models.deletion.PROTECT, to='project_core.PhysicalPerson')),
                ('project', models.ForeignKey(help_text='Abstract containing dates', on_delete=django.db.models.deletion.PROTECT, to='project_core.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
