# Generated by Django 3.0.5 on 2020-04-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant_management', '0021_scientificreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='received_date',
            field=models.DateField(blank=True, help_text='Date the document was received', null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='received_date',
            field=models.DateField(blank=True, help_text='Date the document was received', null=True),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='received_date',
            field=models.DateField(blank=True, help_text='Date the document was received', null=True),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='sent_date',
            field=models.DateField(blank=True, help_text='Date the report was sent to approved', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='received_date',
            field=models.DateField(blank=True, help_text='Date the document was received', null=True),
        ),
        migrations.AlterField(
            model_name='laysummary',
            name='received_date',
            field=models.DateField(blank=True, help_text='Date the document was received', null=True),
        ),
        migrations.AlterField(
            model_name='scientificreport',
            name='received_date',
            field=models.DateField(blank=True, help_text='Date the document was received', null=True),
        ),
        migrations.AlterField(
            model_name='scientificreport',
            name='sent_date',
            field=models.DateField(blank=True, help_text='Date the report was sent to approved', null=True),
        ),
    ]
