# Generated by Django 3.0.5 on 2020-04-30 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grant_management', '0022_promotes_received_date_to_base_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialreport',
            old_name='sent_date',
            new_name='sent_for_approval_date',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='sent_date',
            new_name='sent_for_payment_date',
        ),
        migrations.RenameField(
            model_name='scientificreport',
            old_name='sent_date',
            new_name='sent_for_approval_date',
        ),
    ]
