# Generated by Django 3.0.5 on 2020-05-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant_management', '0024_model_texts_lay_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laysummarytype',
            name='description',
            field=models.CharField(help_text='Description of the type of lay summary', max_length=100),
        ),
        migrations.AlterField(
            model_name='laysummarytype',
            name='name',
            field=models.CharField(help_text='Type of lay summary which could be used within the application to decide how the summary is used', max_length=10, unique=True),
        ),
    ]
