# Generated by Django 3.0.5 on 2020-05-01 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grant_management', '0025_laysummarytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laysummary',
            name='lay_summary_type',
            field=models.ForeignKey(blank=True, help_text='Type of the lay summary', null=True, on_delete=django.db.models.deletion.PROTECT, to='grant_management.LaySummaryType'),
        ),
    ]
