# Generated by Django 3.0.5 on 2020-05-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant_management', '0026_laysummarytype_non_mandatory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='text',
            field=models.TextField(blank=True, help_text='Blog post text', null=True),
        ),
    ]
