# Generated by Django 3.0.5 on 2020-05-08 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0118_calls_need_to_be_part_of_a_funding_instrument'),
        ('grant_management', '0027_bblog_post_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date and time at which the entry was created')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Date and time at which the entry was modified', null=True)),
                ('due_date', models.DateField(help_text='Due date of this instalment')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount of this instalment', max_digits=11)),
                ('project', models.ForeignKey(help_text='Project that this installment refers to', on_delete=django.db.models.deletion.PROTECT, to='project_core.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='installment',
            field=models.ForeignKey(blank=True, help_text='Which installment this invoice refers to', null=True, on_delete=django.db.models.deletion.PROTECT, to='grant_management.Installment'),
        ),
    ]
