# Generated by Django 3.0.5 on 2020-05-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0118_calls_need_to_be_part_of_a_funding_instrument'),
        ('grant_management', '0028_adds_installment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grantagreement',
            name='signed_by',
        ),
        migrations.AddField(
            model_name='grantagreement',
            name='signed_by',
            field=models.ManyToManyField(help_text='People who signed the grant agreement', to='project_core.PhysicalPerson'),
        ),
    ]
