# Generated by Django 3.0.5 on 2020-05-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0118_calls_need_to_be_part_of_a_funding_instrument'),
        ('grant_management', '0029_signed_by_multiple_people'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Media',
            new_name='Medium',
        ),
        migrations.AlterField(
            model_name='grantagreement',
            name='signed_by',
            field=models.ManyToManyField(blank=True, help_text='People who signed the grant agreement', to='project_core.PhysicalPerson'),
        ),
    ]
