# Generated by Django 3.0.5 on 2020-05-12 10:44

from django.db import migrations, models
import django.db.models.deletion
import grant_management.models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0118_calls_need_to_be_part_of_a_funding_instrument'),
        ('grant_management', '0030_renames_media_to_medium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medium',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='medium',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='medium',
            name='modified_on',
        ),
        migrations.RemoveField(
            model_name='medium',
            name='received_date',
        ),
        migrations.AddField(
            model_name='medium',
            name='file',
            field=models.FileField(default=None, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=grant_management.models.medium_file_rename),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medium',
            name='author',
            field=models.ForeignKey(help_text='Person who took the photo', on_delete=django.db.models.deletion.PROTECT, to='project_core.PhysicalPerson'),
        ),
        migrations.AlterField(
            model_name='medium',
            name='license',
            field=models.ForeignKey(help_text='License', on_delete=django.db.models.deletion.PROTECT, to='grant_management.License'),
        ),
        migrations.AlterField(
            model_name='medium',
            name='project',
            field=models.ForeignKey(help_text='Project that this medium belongs to', on_delete=django.db.models.deletion.PROTECT, to='project_core.Project'),
        ),
    ]
