# Generated by Django 3.0.5 on 2020-05-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant_management', '0032_medium_blog_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medium',
            old_name='blog_post',
            new_name='blog_posts',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title',
            field=models.CharField(default=None, help_text='Title of the blogpost', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medium',
            name='received_date',
            field=models.DateField(default=None, help_text='Date that the medium was received'),
            preserve_default=False,
        ),
    ]
