# Generated by Django 3.0.5 on 2020-05-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('grant_management', '0033_adds_date_received_medium_title_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='spdx_identifier',
            field=models.CharField(default=None,
                                   help_text='Identifier as per https://spdx.org/licenses/ CC-BY-NC-SA-4.0',
                                   max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='license',
            name='name',
            field=models.CharField(
                help_text='License name (e.g. Creative Commons Attribution Non Commercial Share Alike 4.0 International)',
                max_length=100, unique=True),
        ),
    ]
