# Generated by Django 3.0.5 on 2020-05-12 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grant_management', '0034_improve_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medium',
            name='license',
            field=models.ForeignKey(blank=True, help_text='License', null=True, on_delete=django.db.models.deletion.PROTECT, to='grant_management.License'),
        ),
    ]
