# Generated by Django 3.0.5 on 2020-05-12 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0118_calls_need_to_be_part_of_a_funding_instrument'),
        ('grant_management', '0036_license_public_text_is_text_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medium',
            name='author',
        ),
        migrations.AddField(
            model_name='medium',
            name='photographer',
            field=models.ForeignKey(default=None, help_text='Person who took the photo/video', on_delete=django.db.models.deletion.PROTECT, to='project_core.PhysicalPerson'),
            preserve_default=False,
        ),
    ]
