# Generated by Django 3.0.5 on 2020-05-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant_management', '0038_medium_descriptive_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medium',
            name='copyright',
            field=models.CharField(blank=True, help_text='Owner of copyright if it is not the photographer (e.g. institution)', max_length=1024, null=True),
        ),
    ]
