# Generated by Django 3.0.5 on 2020-05-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant_management', '0039_medium_copyright_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(blank=True, help_text='Title of the blogpost', max_length=1024, null=True),
        ),
    ]
