# Generated by Django 3.0.5 on 2020-05-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant_management', '0040_blog_post_title_can_be_null_not_received_yet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medium',
            name='blog_posts',
            field=models.ManyToManyField(blank=True, help_text='Which blog posts this image belongs to', to='grant_management.BlogPost'),
        ),
    ]
