# Generated by Django 3.0.5 on 2020-05-13 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0118_calls_need_to_be_part_of_a_funding_instrument'),
        ('grant_management', '0041_allows_media_to_not_be_related_blog_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date and time at which the entry was created')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Date and time at which the entry was modified', null=True)),
                ('url', models.URLField(blank=True, help_text='Address of social media entry (e.g. https://twitter.com/SwissPolar)', null=True)),
                ('project', models.ForeignKey(help_text='Choose related project', on_delete=django.db.models.deletion.PROTECT, to='project_core.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='date_published',
            new_name='published_date',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='date_time_published',
        ),
        migrations.AddField(
            model_name='publication',
            name='published_date',
            field=models.DateField(blank=True, help_text='Date of the publication', null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='doi',
            field=models.CharField(blank=True, help_text='DOI reference for entry', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='title',
            field=models.CharField(help_text='Dataset title', max_length=1000),
        ),
        migrations.AlterField(
            model_name='publication',
            name='doi',
            field=models.CharField(blank=True, help_text='DOI reference for entry', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='reference',
            field=models.CharField(blank=True, help_text='Journal reference for entry', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(help_text='Publication title', max_length=1000),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='name',
            field=models.CharField(help_text='Please enter social network title (e.g. Twitter, Facebook, Instagram, Blog)', max_length=100),
        ),
        migrations.DeleteModel(
            name='ProjectSocialMedia',
        ),
        migrations.AddField(
            model_name='projectsocialnetwork',
            name='social_network',
            field=models.ForeignKey(help_text='Choose the related social network', on_delete=django.db.models.deletion.PROTECT, to='grant_management.SocialNetwork'),
        ),
    ]
