# Generated by Django 3.0.5 on 2020-05-19 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grant_management', '0044_historicalmilestone_milestone_milestonecategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalmilestone',
            old_name='milestone_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='milestone',
            old_name='milestone_category',
            new_name='category',
        ),
    ]
