# Generated by Django 3.0.5 on 2020-05-19 13:57

from django.db import migrations


def add_social_networks(apps, schema_editor):
    SocialNetwork = apps.get_model('grant_management', 'SocialNetwork')

    for social_network_name in ['Blog', 'Facebook', 'Instagram', 'Mastodon', 'Pinterest', 'Twitter', 'Web Page']:
        SocialNetwork.objects.get_or_create(name=social_network_name)


class Migration(migrations.Migration):
    dependencies = [
        ('grant_management', '0045_milestone_category_to_category'),
    ]

    operations = [
        migrations.RunPython(add_social_networks),
    ]
