# Generated by Django 3.0.5 on 2020-05-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant_management', '0046_add_social_media_networks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Installment amount', max_digits=11),
        ),
        migrations.AlterField(
            model_name='installment',
            name='due_date',
            field=models.DateField(help_text='Due date of this installment'),
        ),
    ]
