# Generated by Django 3.0.5 on 2020-05-27 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grant_management', '0047_installment_help_texts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='installment',
            field=models.ForeignKey(blank=True, help_text='Installment to which the invoice is assigned', null=True, on_delete=django.db.models.deletion.PROTECT, to='grant_management.Installment'),
        ),
    ]
