# Generated by Django 3.0.5 on 2020-06-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant_management', '0048_installment_helptext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestonecategory',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
