# Generated by Django 3.0.7 on 2020-06-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant_management', '0049_milestone_category_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installment',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='due_date',
            field=models.DateField(blank=True, help_text='Date the document is due', null=True),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='due_date',
            field=models.DateField(blank=True, help_text='Date the document is due', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, help_text='Date the document is due', null=True),
        ),
        migrations.AlterField(
            model_name='laysummary',
            name='due_date',
            field=models.DateField(blank=True, help_text='Date the document is due', null=True),
        ),
        migrations.AlterField(
            model_name='scientificreport',
            name='due_date',
            field=models.DateField(blank=True, help_text='Date the document is due', null=True),
        ),
    ]
