# Generated by Django 3.0.7 on 2020-06-17 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grant_management', '0050_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='allow_overbudget',
            field=models.BooleanField(default=False, help_text='This invoice takes a payment overbudget'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='overbudget_allowed_by',
            field=models.ForeignKey(help_text='User that allowed the overbudget', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
