# Generated by Django 3.0.10 on 2020-09-21 10:38

from django.db import migrations, models
import grant_management.models
import project_core.utils.utils
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('grant_management', '0052_invoice_allow_overbudget_by_can_be_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialreport',
            name='file',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=grant_management.models.finance_report_file_rename, validators=[*project_core.utils.utils.management_file_validator()]),
        ),
        migrations.AlterField(
            model_name='grantagreement',
            name='file',
            field=models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=grant_management.models.grant_agreement_file_rename, validators=[*project_core.utils.utils.management_file_validator()]),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='file',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=grant_management.models.invoice_file_rename, validators=[*project_core.utils.utils.management_file_validator()]),
        ),
        migrations.AlterField(
            model_name='medium',
            name='file',
            field=models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=grant_management.models.medium_file_rename, validators=[*project_core.utils.utils.management_file_validator()]),
        ),
        migrations.AlterField(
            model_name='scientificreport',
            name='file',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=grant_management.models.scientific_report_file_rename, validators=[*project_core.utils.utils.management_file_validator()]),
        ),
    ]
