# Generated by Django 3.0.10 on 2020-10-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant_management', '0054_medium_add_createmodified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medium',
            options={'verbose_name_plural': 'Media'},
        ),
        migrations.AddField(
            model_name='medium',
            name='md5_sum',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
