# Generated by Django 3.0.10 on 2020-10-12 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grant_management', '0055_add_md5_to_medium'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medium',
            old_name='md5_sum',
            new_name='file_md5',
        ),
    ]
