# Generated by Django 3.0.10 on 2020-10-12 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grant_management', '0056_rename_file_field_medium'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediumDeleted',
            fields=[
                ('medium_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='grant_management.Medium')),
            ],
            options={
                'verbose_name_plural': 'MediaDeleted',
            },
            bases=('grant_management.medium',),
        ),
    ]
