# Generated by Django 3.2.3 on 2021-05-24 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grant_management', '0057_mediumdeleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laysummary',
            options={'verbose_name_plural': 'Lay Summaries'},
        ),
    ]
