# Generated by Django 3.2.5 on 2021-11-25 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0167_organisation_display_name'),
        ('grant_management', '0059_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='project',
            field=models.ForeignKey(help_text='Abstract containing dates', on_delete=django.db.models.deletion.PROTECT, related_name='project_blogpost', to='project_core.project'),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='project',
            field=models.ForeignKey(help_text='Abstract containing dates', on_delete=django.db.models.deletion.PROTECT, related_name='project_financialreport', to='project_core.project'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='project',
            field=models.ForeignKey(help_text='Abstract containing dates', on_delete=django.db.models.deletion.PROTECT, related_name='project_invoice', to='project_core.project'),
        ),
        migrations.AlterField(
            model_name='laysummary',
            name='project',
            field=models.ForeignKey(help_text='Abstract containing dates', on_delete=django.db.models.deletion.PROTECT, related_name='project_laysummary', to='project_core.project'),
        ),
        migrations.AlterField(
            model_name='medium',
            name='project',
            field=models.ForeignKey(help_text='Project that this medium belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='project_medium', to='project_core.project'),
        ),
        migrations.AlterField(
            model_name='scientificreport',
            name='project',
            field=models.ForeignKey(help_text='Abstract containing dates', on_delete=django.db.models.deletion.PROTECT, related_name='project_scientificreport', to='project_core.project'),
        ),
    ]
