# Generated by Django 3.2.9 on 2021-12-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant_management', '0060_unique_together_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='medium',
            name='key_image',
            field=models.BooleanField(default=False, help_text='Select as a key image to be displayed on website'),
        ),
        migrations.AddField(
            model_name='medium',
            name='primary_image',
            field=models.BooleanField(default=False, help_text='Select as a primary image on website'),
        ),
    ]
