# Generated by Django 3.2.12 on 2022-03-25 09:15

from django.db import migrations, models
import grant_management.models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('grant_management', '0061_key_and_primary_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='medium',
            name='file_web',
            field=models.FileField(null=True, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=grant_management.models.medium_file_rename),
        ),
    ]
