# Generated by Django 3.2.13 on 2022-04-26 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0177_add_on_webite_field'),
        ('grant_management', '0062_add_file_web'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date and time at which the entry was created')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Date and time at which the entry was modified', null=True)),
                ('url', models.URLField(blank=True, help_text='URL of fieldnote', null=True)),
                ('title', models.CharField(help_text='Title of fieldnote', max_length=1000)),
                ('project', models.ForeignKey(help_text='Project to which is the fieldnote is related', on_delete=django.db.models.deletion.PROTECT, to='project_core.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
