# Generated by Django 3.2.13 on 2022-06-29 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0177_add_on_webite_field'),
        ('grant_management', '0065_coinvestors_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coinvestors',
            old_name='co_investor',
            new_name='co_investigator',
        ),
        migrations.AlterField(
            model_name='coinvestors',
            name='project',
            field=models.ForeignKey(help_text='Project to which the publication is related', on_delete=django.db.models.deletion.PROTECT, related_name='project_person', to='project_core.project'),
        ),
    ]
