# Generated by Django 3.2.13 on 2022-07-08 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0178_auto_20220708_0904'),
        ('grant_management', '0066_auto_20220629_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinvestors',
            name='co_investigator',
            field=models.ForeignKey(blank=True, help_text='Co-Investigator', null=True, on_delete=django.db.models.deletion.PROTECT, to='project_core.physicalperson'),
        ),
    ]
