# Generated by Django 3.2.13 on 2022-07-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant_management', '0067_alter_coinvestors_co_investigator'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinvestors',
            name='organisation_text',
            field=models.CharField(blank=True, help_text='Organisation Text', max_length=100, null=True),
        ),
    ]
