# Generated by Django 3.2.14 on 2022-10-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant_management', '0068_coinvestors_organisation_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinvestors',
            name='organisation_text',
            field=models.CharField(blank=True, help_text='if organisation not found add here', max_length=100, null=True),
        ),
    ]
