# Generated by Django 3.2.15 on 2022-10-19 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0179_trace_tracecoordinates'),
        ('grant_management', '0069_alter_coinvestors_organisation_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Underspending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date and time at which the entry was created')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Date and time at which the entry was modified', null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Underspending amount', max_digits=11)),
                ('project', models.ForeignKey(help_text='Project that this underspending refers to', on_delete=django.db.models.deletion.PROTECT, to='project_core.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
