# Generated by Django 3.2.16 on 2022-11-07 16:15

from django.db import migrations, models
import django.db.models.deletion
import grant_management.models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0180_auto_20221104_1341'),
        ('grant_management', '0070_underspending'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsocialnetwork',
            name='file',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=grant_management.models.outreach_file_rename),
        ),
        migrations.AlterField(
            model_name='projectsocialnetwork',
            name='project',
            field=models.ForeignKey(help_text='Project to which this outreach page is related', on_delete=django.db.models.deletion.PROTECT, to='project_core.project'),
        ),
        migrations.AlterField(
            model_name='projectsocialnetwork',
            name='social_network',
            field=models.ForeignKey(help_text='Outreach with information about the project', on_delete=django.db.models.deletion.PROTECT, to='grant_management.socialnetwork'),
        ),
        migrations.AlterField(
            model_name='projectsocialnetwork',
            name='url',
            field=models.URLField(blank=True, help_text='URL of outreach (e.g. https://twitter.com/SwissPolar)', null=True),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='name',
            field=models.CharField(help_text='Outreach name (e.g. Twitter, Facebook, Instagram, Blog)', max_length=100),
        ),
    ]
