# Generated by Django 3.2.18 on 2023-04-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant_management', '0072_auto_20230213_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='medium',
            name='uploaded',
            field=models.BooleanField(default=False, help_text='Uploaded to media gallery'),
        ),
    ]
