# Generated by Django 3.2.23 on 2024-05-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant_management', '0075_dataset_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medium',
            name='photographer',
            field=models.CharField(help_text='Person who took the photo/video', max_length=256),
        ),
    ]
