# Generated by Django 3.2.23 on 2025-03-05 03:53

from django.db import migrations, models
import django.db.models.deletion
import grant_management.models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0194_auto_20250305_0453'),
        ('grant_management', '0076_alter_medium_photographer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonEmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date and time at which the entry was created')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Date and time at which the entry was modified', null=True)),
                ('file', models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=grant_management.models.carbon_emission_file_rename)),
                ('text', models.CharField(blank=True, max_length=200, null=True)),
                ('project', models.ForeignKey(help_text='Project that the coordinate belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='project_carbonemission', to='project_core.project')),
            ],
            options={
                'unique_together': {('project', 'file', 'text')},
            },
        ),
    ]
