# Generated by Django 3.2.23 on 2025-03-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0194_auto_20250305_0453'),
        ('grant_management', '0077_carbonemission'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbonemission',
            name='effective_carbon_emission',
            field=models.CharField(blank=True, help_text='Effective Carbon Emission', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='carbonemission',
            name='estimate_carbon_emission',
            field=models.CharField(blank=True, help_text='Estimate Carbon Emission', max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='carbonemission',
            unique_together={('project', 'file', 'estimate_carbon_emission', 'effective_carbon_emission')},
        ),
        migrations.RemoveField(
            model_name='carbonemission',
            name='text',
        ),
    ]
