# Generated by Django 3.2.23 on 2025-05-19 10:10

from django.db import migrations, models
import grant_management.models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('grant_management', '0078_auto_20250310_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbonemission',
            name='effective_carbon_emission_file',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=grant_management.models.effective_carbon_emission_file_rename),
        ),
    ]
