# Generated by Django 2.2.6 on 2020-02-13 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the colour', max_length=64, unique=True)),
                ('hex_code', models.CharField(help_text='Hex code, e.g. FF0000 for red', max_length=7, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ColourPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='For example "Red background with grey text" or "Use for alerts"', max_length=128, unique=True)),
                ('background_colour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colorpair_background', to='colours.Colour')),
                ('text_colour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colorpair_text', to='colours.Colour')),
            ],
        ),
    ]
