# Generated by Django 2.2.6 on 2020-02-13 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colours', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colourpair',
            old_name='background_colour',
            new_name='background',
        ),
        migrations.RenameField(
            model_name='colourpair',
            old_name='text_colour',
            new_name='text',
        ),
    ]
