# Generated by Django 2.2.6 on 2020-01-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatevariablename',
            name='default',
            field=models.CharField(default='', help_text="Default value if a Call doesn't override it", max_length=200),
            preserve_default=False,
        ),
    ]
